# ============================================================
# SealedSecret — Backup R2 Credentials
# ============================================================
# Cloudflare R2 credentials for backup CronJobs (db, redis, opensearch).
# Regenerate: kubeseal on VPS with --controller-name sealed-secrets-controller
# ============================================================
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-r2-credentials
  namespace: hire-adda
  labels:
    app: backups
    app.kubernetes.io/name: backups
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: hire-adda
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCcpFQ8FDjLkxEjSEdAEFE5EIvKTph9y7AFgXzXrmJ63H36hai8BSXXlMiaLBA+7sBzbGwOeqc5NuLnuxTezxqGJg9KIPKf8HTSEARvXDJKwpgUwMO6a3GHqHZ1IUI7y/MfP8Iff9s+TX/8k2phC8vVLrB7O5S9wJDV8vD1c6Es8jcX3hGLOpVcUQ1QmUFEkzScitfe88xsE/F8xMVQwhOzryG5ujxdDuTAS6Flsne5V12vdiPRAVzdUulQyBo9bmvrbqpYuZcMtyBtX5KwozrE9zai6NjTFZueba4reLbruzzGW5WtRVyo14QX3/FeE+JzMNKHTlVSuLyRfPyDV31hIERNRb23ddAbp/yjrgosgKPlQckGgWBN7PlEGM85Sgo4EKZgbVyisfLTNukkwGOsrT3qKCTU0gbWtGxFLYBeqHZYAbZOs0W48zOlPbuw7I+wZ2MpmanyWNbImfKh9enHfrCSZ8QDiMzRxHzV6LSA18WIkJPyL8H0kXfcvfBQjtZPyihBePwJzTGsUAVzwAYpWz31Q4zaVEDmcmHmSEr4fBfhRkSh4bxhBP1I9Qsk5y284SiIogQaRY3TWiiPBSCfrmv8M3OafePsW3j0FgNROi+JNGULozOuKlYyo6pKfCDMqSOerqsi3XAK4aztjCoDGS1xdBOKyG0pTz0Lee/Dk//E5Xl0m90rzy8aCEu6NIPJhXyr2wilt/2aWKv14QZMzl311pH8NeS1n9+qP9/jQQ==
    AWS_SECRET_ACCESS_KEY: AgCXgZ9esDyzg6l2u/ng4zZBDgJripxyOHz0FwM38giE5v1bnrjQQOEQ73qT1VaLxenFpe5anGSVpqmpFMBjv7kCK+0XAlE9etM89vuD7GDffuwcINh77WXkobIU57Def3/cSW02VKsJIoQVdFUwcoWzWeOyWn1KihY/Br/+F5n51kIwurv4kp2NdIWo9KQy9H6jIspqtQE3lob+6xwU0sjzPO7K065wz+kAZfamjDPt/oh+/RUHfPP8Y+KeGli6dy88Ou+kfR3ABjZ43vk6GKikvMOwK7eP4TjGd+A/2KKsEGC4CGGN0UD/t9b17khq5SQI+Me2fsCENXyLze3/Ak6Tn+beQiCCBofPSEMba5/SccafO6qtDdgD53GTv4uY6+XbSypoeZHK8W+GRrBnWqdv2bTTcySiBU1R8tBkbITPzEvmKTRJdjt/VVAWiZXBeIMzfHBidZJNUVat3Q3HVAZBI91G8lIGk9jTtMZ2o0L+BN5SZ9UBgx2DWoBE6BnzbKVpGIbacvZzuqJvjnEgY3FVamIlgvpMNjsN89BpeGoGoumjpuR/yxZr7kRZWBg6DumCOTcyj4UfYCTdaTS8KZRQSTj7+t8lGU9+BqGPaFkc+DNc+iSIBTJnoFx960l255cqkDrdC3Q3HZC6qoOUyDuYrY0a6iJKAPsEKchzZje599tgBStrmVDbPlFh6tRW6YWnxgHSNTKXb4Jujcy1x7qHB7d76BbSrHzpLwOVZwZdaDveHkOpmIcMueKQLVDrT8cEOomL5lCtC3W64GaB8h+a
  template:
    metadata:
      name: backup-r2-credentials
      namespace: hire-adda
      labels:
        app: backups
        app.kubernetes.io/name: backups
        app.kubernetes.io/component: backup
        app.kubernetes.io/part-of: hire-adda
    type: Opaque
