---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: hire-adda
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCH2EKPQOgfzhW+NuCT95UHjEC6tlj1BcHrsX3cz4psTRsUw2x+3QT/M92dA7TiiyDp8izigkOgVoqO0PBUJFqhmJIoMR4qMQ87BItEcJl99B0rs2JRvPkticgxBBjXX7qUsjryMWCEafm3NBQjsKkvyztJbysnjwvj2a9w9xpLNahyP0lYVGVNbO19QhjIWNOfsNFtr3xhZE7+DC6pw3xmUPOLlWX6MW+oq9ZCoOfy2HzK7bWz+5SdBy3ZbMjhK0NZSzhgHcaJnLbXh8SiraG7dINTYkil5upX+DnvSi25Z4E+dA7cfsWNvadZLgE5HX/DD1zF1PRWDVj60doZ0jE1Y2L14b+iI/DULuOOIEUlNZuc7GRE3P0JdFLOeH4fHQehLr+j+DUFNPBa/sa9w218b9qj4F23nEc4FZZN9NVb5oHluFExCElVq1r46DwHCPDKagWEic6c2fBcLZQ3DEWFwqmpcHFxc4CuT0voOE/2tELdP9PwGVk3etM4vLlcAkGR5UwEo8b0+jtxA78ZOcASgQpKK6OqRHvsTCAnTgg+aCWKuYpQya3XWUKd8nPKvrmutBuDhV8uoIc2FwLofD1GYSMysIR8nd2yNkZC4D1GDPYwUBWheAg4Whr0Rz0eoGiwN17wjua3b4pabF28sPL1baBV+ZNKPS98e/PMcowW22KmV/OwD4/mXYnZVMqXGag=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: hire-adda
