# ============================================================
# SealedSecret — Velero R2 Backup Credentials
# ============================================================
# Contains Cloudflare R2 credentials in AWS-format for Velero.
# Regenerate: kubeseal on VPS with --controller-name sealed-secrets-controller
# ============================================================
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-r2-credentials
  namespace: velero
  labels:
    app: velero
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: hire-adda
spec:
  encryptedData:
    cloud: AgDAob29p0MPLYJwmrX5h9iDWGyc7raubz/KojvVVkPKMs0cagZIuSrC09X6RZqUcJCKNzP+IKkiWZsTUC3L1Vy5UANtvgMniuzodd1isxO3bb1AT4Nvf9EQexKWtrmtZBzncwnDBWfLO/q1Vqvu80jRbYag6UxanXbCew+Xs1s5ud9rmHOXcOIpNCkTzZvNjsAt6d/CUp/q0BssHzM+ucohtIILEeuuk0I4e+p50CiUhU1sDU38zCCIvFVxm/70YlWW1KQJ5esA7I7fzpUArvNZEphzAgioTln7MqcOYbrVih2Nf/QeqaWZlH8v354n+jIBl2UjqRLbu5wKqRexCFeubOGxOi3zeDVKwuWGkZoLr2DFB5A6nCvsKFgvHrUxg+Dr0ASud+TS/6dbyEWyChxRMEcBLLewIFH3Y/N8E5DXx5aPHN5o9pvdCEspUcmZhx0JoDo74HX6zBziAAk4KYCh5XOMsuBjq3nG8YK9tvNQcxSfAoe33Cg+0Ov9cJUsbh1WUvaYaaCxzHn5tz7PjA3734q2/qDwuMIoA8sBEnMzhokaHe0sCDPIxhWF6hgU9P+dtkhSHBfBvnrGgQuVYBou4Ng5/RkviM1PcK5hpGUO/ACgvYselaY0T+gSXKwFzV9BVP+68nIzhlozZLn5e3kbrVJlb3Y3SyrUG4zfjq470seRY9dum1681w0DrrFjfj7i9inv5tO8jrV7XymlL1O+n7VB/3aiAIAyYaB/XKE7Qrr+f2832qTAMT8rVI3oREU+xoPGrlXDb7GYirr4OVQToc7v3lDapYbht8lSV5dUzr4mVgF7vMZO/61G5TVNAJwfTBPagPkJqiV/CkHO1kXqRwcmu9YhG0FVbhDi7tfho1AHbeT34+qv83F/ywidPVlLIy5/znC1RA==
  template:
    metadata:
      name: velero-r2-credentials
      namespace: velero
      labels:
        app: velero
        app.kubernetes.io/name: velero
        app.kubernetes.io/component: backup
        app.kubernetes.io/part-of: hire-adda
    type: Opaque
