export const API = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    REFRESH_TOKEN: '/auth/refresh-token',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_EMAIL_VERIFICATION: '/auth/resend-email-verification',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD_INITIATE: '/auth/change-password/initiate',
    CHANGE_PASSWORD_CONFIRM: '/auth/change-password/confirm',
    LOGOUT_EVERYWHERE: '/auth/logout-everywhere',
    MFA_SETUP: '/auth/mfa/setup',
    MFA_ENABLE: '/auth/mfa/enable',
    MFA_DISABLE: '/auth/mfa/disable',
    MFA_REGENERATE_BACKUP: '/auth/mfa/backup-codes',
    MFA_BACKUP_CODE_COUNT: '/auth/mfa/backup-codes/count',
    VERIFY_MOBILE: '/auth/verify-mobile',
    RESEND_MOBILE_OTP: '/auth/resend-mobile-otp',
    VERIFY_WHATSAPP: '/auth/verify-whatsapp',
    VERIFY_WHATSAPP_OTP: '/auth/verify-whatsapp-otp',
    CHANGE_WHATSAPP_NUMBER: '/auth/change-whatsapp-number',
    REMOVE_WHATSAPP_NUMBER: '/auth/whatsapp-number',
    CHANGE_EMAIL_INITIATE: '/auth/change-email/initiate',
    CHANGE_EMAIL_CONFIRM: '/auth/change-email/confirm',
    CHANGE_EMAIL_RESEND_OTP: '/auth/change-email/resend-otp',
    CHANGE_MOBILE_INITIATE: '/auth/change-mobile/initiate',
    CHANGE_MOBILE_CONFIRM: '/auth/change-mobile/confirm',
    CHANGE_MOBILE_RESEND_OTP: '/auth/change-mobile/resend-otp',
    FIREBASE_LOGIN: '/auth/firebase-login',
    GOOGLE: '/auth/google',
    LINKEDIN: '/auth/linkedin',
  },
  CANDIDATES: {
    ME: '/candidates/me',
    DASHBOARD: '/candidates/me/dashboard',
    COMPLETENESS: '/candidates/me/completeness',
    RESUME: '/candidates/me/resume',
    RESUME_GENERATE: '/candidates/me/resume/generate',
    RESUME_READINESS: '/candidates/me/resume/readiness',
    RESUME_USE_GENERATED: '/candidates/me/resume/use-generated',
    AVATAR: '/candidates/me/avatar',
    PROFILE_VIEWS: '/candidates/me/profile-views',
    SEARCH: '/candidates',
    DETAIL: (id: string) => `/candidates/${id}`,
    RESUME_DOWNLOAD: (id: string) => `/candidates/${id}/resume`,
  },
  EMPLOYERS: {
    DASHBOARD: '/employers/dashboard',
    ME: '/employers/me',
    LOGO: '/employers/me/logo',
    PROFILE_VIEWS: '/employers/me/profile-views',
    ENGAGEMENT_METRICS: '/employers/engagement-metrics',
    COMPLETENESS: '/employers/me/completeness',
    ANALYTICS: '/employers/analytics',
    ANALYTICS_EXPORT: '/employers/analytics/export',
    SEARCH_CANDIDATES: '/employers/candidates/search',
    SAVE_CANDIDATE: (id: string) => `/saved-candidates/${id}/toggle`, // Matches saved-candidate.routes.ts
    SAVED_CANDIDATES: '/saved-candidates', // Matches saved-candidate.routes.ts
    SAVED_CANDIDATE_NOTES: (id: string) => `/saved-candidates/${id}/notes`,
    SHORTLIST_CANDIDATE: (candidateId: string) => `/employers/candidates/${candidateId}/shortlist`,
    SELECT_CANDIDATE: (candidateId: string) => `/employers/candidates/${candidateId}/select`,
    BULK_EXPORT_CANDIDATES: '/employers/candidates/bulk-export',
    CANDIDATE_MATCH_SCORE: (candidateId: string, jobId: string) =>
      `/employers/candidates/${candidateId}/match/${jobId}`,
    SIMILAR_CANDIDATES: (candidateId: string) => `/employers/candidates/${candidateId}/similar`,
    APPLICATIONS: '/employers/applications',
  },
  JOBS: {
    SEARCH: '/jobs',
    DETAIL: (id: string) => `/jobs/${id}`,
    CREATE: '/jobs',
    UPDATE: (id: string) => `/jobs/${id}`,
    DEACTIVATE: (id: string) => `/jobs/${id}/deactivate`,
    APPLY: (id: string) => `/jobs/${id}/apply`,
    SAVE: (id: string) => `/jobs/${id}/save`,
    SAVED: '/jobs/saved',
    APPLIED: '/jobs/applications/me',
    MY_JOBS: '/jobs/employer/my-jobs',
    APPLICATIONS: (jobId: string) => `/jobs/${jobId}/applications`,
    UPDATE_APPLICATION: (applicationId: string) => `/jobs/applications/${applicationId}`,
    APPLICATION_DETAIL: (applicationId: string) => `/jobs/applications/${applicationId}`,
    WITHDRAW_APPLICATION: (applicationId: string) => `/jobs/applications/${applicationId}/withdraw`,
    CLONE: (id: string) => `/jobs/${id}/clone`,
  },
  JOB_TEMPLATES: {
    LIST: '/employers/job-templates',
    CREATE: '/employers/job-templates',
    UPDATE: (id: string) => `/employers/job-templates/${id}`,
    DELETE: (id: string) => `/employers/job-templates/${id}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    UNREAD_COUNT: '/notifications/unread-count',
  },
  SESSIONS: {
    LIST: '/sessions',
    REVOKE: (id: string) => `/sessions/${id}`,
    REVOKE_ALL: '/sessions',
  },
  DRAFTS: {
    SAVE: '/drafts',
    LIST: '/drafts',
    DETAIL: (id: string) => `/drafts/${id}`,
    DELETE: (id: string) => `/drafts/${id}`,
  },
  ADMIN: {
    STATS: '/admin/stats',
    COMPREHENSIVE_STATS: '/admin/stats/comprehensive',
    ACTIVITY: '/admin/activity',
    USERS: '/admin/users',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    DELETE_USER: (id: string) => `/admin/users/${id}`,
    SUSPEND_USER: (id: string) => `/admin/users/${id}/suspend`,
    ACTIVATE_USER: (id: string) => `/admin/users/${id}/activate`,
    UPDATE_USER_ROLE: (id: string) => `/admin/users/${id}/role`,
    MODERATE_JOB: (id: string) => `/admin/jobs/${id}/status`,
    FLAG_JOB: (id: string) => `/admin/jobs/${id}/flag`,
    ANALYTICS: '/admin/analytics',
    AUDIT_LOGS: '/admin/audit-logs',
    EMAIL_TEMPLATES: '/admin/email-templates',
    EMAIL_TEMPLATES_PREVIEW: '/admin/email-templates/preview',
    EMAIL_TEMPLATES_TEST: '/admin/email-templates/test',
    KAFKA_EVENTS: '/admin/kafka-events',
    LIVE_COUNTERS: '/admin/live-counters',
    DAILY_ACTIVE_USERS: '/admin/stats/daily-active-users',
    MODERATION_KEYWORDS: '/admin/moderation/keywords',
    MODERATION_KEYWORD_DELETE: (keyword: string) =>
      `/admin/moderation/keywords/${encodeURIComponent(keyword)}`,
    JOBS: '/admin/jobs',
    DELETE_JOB: (id: string) => `/admin/jobs/${id}`,
    APPLICATIONS: '/admin/applications',
    APPLICATION_STATS: '/admin/applications/stats',
    REPORTS: {
      USERS: '/reports/users/export',
      JOBS: '/reports/jobs/export',
      ANALYTICS: '/reports/analytics/export',
    },
  },
  SUPER_ADMIN: {
    CREATE_ADMIN: '/super-admin/admins',
    LIST_ADMINS: '/super-admin/admins',
    REMOVE_ADMIN: (id: string) => `/super-admin/admins/${id}`,
    GET_CONFIG: '/super-admin/config',
    UPDATE_CONFIG: '/super-admin/config',
    CREATE_USER: '/super-admin/users',
    UPDATE_USER_PROFILE: (id: string) => `/super-admin/users/${id}/profile`,
    SEND_PASSWORD_RESET_OTP: (id: string) => `/super-admin/users/${id}/password-otp`,
    RESET_USER_PASSWORD: (id: string) => `/super-admin/users/${id}/password`,
    DEACTIVATE_USER: (id: string) => `/super-admin/users/${id}/deactivate`,
    UPLOAD_USER_AVATAR: (id: string) => `/super-admin/users/${id}/avatar`,
    REMOVE_USER_AVATAR: (id: string) => `/super-admin/users/${id}/avatar`,
    USER_SESSIONS: (id: string) => `/super-admin/users/${id}/sessions`,
    REVOKE_USER_SESSIONS: (id: string) => `/super-admin/users/${id}/sessions`,
    MFA_SETUP: (id: string) => `/super-admin/users/${id}/mfa/setup`,
    MFA_ENABLE: (id: string) => `/super-admin/users/${id}/mfa/enable`,
    MFA_DISABLE: (id: string) => `/super-admin/users/${id}/mfa/disable`,
    MFA_STATUS: (id: string) => `/super-admin/users/${id}/mfa/status`,
    MFA_REGEN_BACKUP: (id: string) => `/super-admin/users/${id}/mfa/backup-codes`,
  },
  DEVICES: {
    FCM: '/devices/fcm',
    FCM_DELETE: (tokenId: string) => `/devices/fcm/${tokenId}`,
    PUSH_SUBSCRIPTIONS: '/devices/push-subscriptions',
    PUSH_SUBSCRIPTION_DELETE: (id: string) => `/devices/push-subscriptions/${id}`,
  },
  VERIFICATIONS: {
    REQUEST: '/verifications/request',
    MINE: '/verifications/mine',
    PENDING: '/verifications/pending',
    ALL: '/verifications/all',
    STATS: '/verifications/stats',
    REVIEW: (id: string) => `/verifications/${id}/review`,
    ESCALATE: (id: string) => `/verifications/${id}/escalate`,
    EMPLOYMENT_CONTACT: (id: string) => `/verifications/${id}/employment-contact`,
    EMPLOYMENT_RESPONSE: (token: string) => `/verifications/employment-response/${token}`,
    SET_SLA: (id: string) => `/verifications/${id}/sla`,
    SET_APPROVAL_CHAIN: (id: string) => `/verifications/${id}/approval-chain`,
    APPROVE_LEVEL: (id: string) => `/verifications/${id}/approve-level`,
  },
  SAVED_SEARCHES: {
    CREATE: '/saved-searches',
    LIST: '/saved-searches',
    UPDATE: (id: string) => `/saved-searches/${id}`,
    DELETE: (id: string) => `/saved-searches/${id}`,
  },
  SEARCH: {
    AUTOCOMPLETE: '/search/autocomplete',
    SUGGEST: '/search/suggest',
    SUGGEST_SKILLS: '/search/suggest/skills',
    SUGGEST_LOCATIONS: '/search/suggest/locations',
    SUGGEST_COMPANIES: '/search/suggest/companies',
    SUGGEST_TITLES: '/search/suggest/titles',
    DID_YOU_MEAN: '/search/did-you-mean',
    HISTORY: '/search/history',
    POPULAR: '/search/popular',
    FIELD_HISTORY: (field: string) => `/search/field-history/${field}`,
  },
  FEATURE_FLAGS: {
    CLIENT: '/feature-flags/client',
    ALL: '/feature-flags',
  },
  WEBAUTHN: {
    REGISTER_OPTIONS: '/webauthn/register/options',
    REGISTER_VERIFY: '/webauthn/register/verify',
    LOGIN_OPTIONS: '/webauthn/login/options',
    LOGIN_VERIFY: '/webauthn/login/verify',
    CREDENTIALS: '/webauthn/credentials',
  },
  WEBHOOKS: {
    BASE: '/webhooks',
    DETAIL: (id: string) => `/webhooks/${id}`,
    DELIVERIES: (id: string) => `/webhooks/${id}/deliveries`,
    TEST: (id: string) => `/webhooks/${id}/test`,
  },
  CANDIDATES_EXTRA: {
    PARSE_RESUME: '/candidates/me/resume/parse',
    PARSED_RESUME: '/candidates/me/resume/parsed',
    ANALYTICS: '/candidates/me/analytics',
    ANALYTICS_EXPORT: '/candidates/me/analytics/export',
    JOB_ALERTS: '/candidates/me/job-alerts',
    JOB_ALERT_DETAIL: (id: string) => `/candidates/me/job-alerts/${id}`,
    JOB_ALERT_MATCHES: (id: string) => `/candidates/me/job-alerts/${id}/matches`,
  },
  RECOMMENDATIONS: {
    JOBS: '/recommendations/jobs',
    CANDIDATES: (jobId: string) => `/recommendations/candidates/${jobId}`,
    CANDIDATES_FOR_EMPLOYER: '/recommendations/candidates',
    DISMISS_JOB: (jobId: string) => `/recommendations/jobs/${jobId}/dismiss`,
  },
  ADVANCED_ANALYTICS: {
    USER_GROWTH: '/analytics/advanced/user-growth',
    APPLICATION_FUNNEL: '/analytics/advanced/application-funnel',
    POPULAR_SKILLS: '/analytics/advanced/popular-skills',
    SALARY_TRENDS: '/analytics/advanced/salary-trends',
    JOB_TRENDS: '/analytics/advanced/job-trends',
  },
  CONTACT: {
    SUBMIT: '/contact',
  },
  TICKETS: {
    CREATE: '/tickets',
    GUEST_CREATE: '/tickets/guest',
    MY_TICKETS: '/tickets/my-tickets',
    ALL: '/tickets/all',
    DETAIL: (id: string) => `/tickets/${id}`,
    BY_NUMBER: (num: string) => `/tickets/by-number/${num}`,
    MESSAGES: (id: string) => `/tickets/${id}/messages`,
    ASSIGN: (id: string) => `/tickets/${id}/assign`,
    STATUS: (id: string) => `/tickets/${id}/status`,
    CLOSE: (id: string) => `/tickets/${id}/close`,
    REOPEN: (id: string) => `/tickets/${id}/reopen`,
    SATISFACTION: (id: string) => `/tickets/${id}/satisfaction`,
    STATS: '/tickets/stats',
    ANALYTICS: '/tickets/analytics',
  },
  CONFIG: {
    OTP: '/config/otp',
    SECURITY: '/config/security',
  },
  PUBLIC_STATS: '/public/stats',
  PUBLIC_JOB_CATEGORY_COUNTS: '/public/jobs/category-counts',
  HEALTH: '/health',
} as const;
