export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    HELP: '/help',
    /**
     * Human-readable site map page. URL is `/site-map` (dashed) because the
     * undashed `/sitemap` conflicts with the `sitemap.xml` metadata file —
     * having both an `app/sitemap/` folder (route segment) and an
     * `app/sitemap.ts` (metadata file) causes Next.js to drop the `.xml`
     * index. Renaming the HTML route removes the shadow without touching
     * the XML sitemap.
     */
    SITEMAP: '/site-map',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    COOKIE_POLICY: '/cookie-policy',
    REFUND_POLICY: '/refund-policy',
    ACCESSIBILITY: '/accessibility',
    DISCLAIMER: '/disclaimer',
    COMPANY: (id: string) => `/company/${id}`,
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
  },
  CANDIDATE: {
    DASHBOARD: '/candidate',
    ONBOARDING: '/candidate/onboarding',
    ANALYTICS: '/candidate/analytics',
    PROFILE: '/candidate/profile',
    PROFILE_PREVIEW: '/candidate/profile/preview',
    JOBS: '/candidate/jobs',
    JOB_DETAIL: (id: string) => `/candidate/jobs/${id}`,
    RECOMMENDATIONS: '/candidate/recommendations',
    APPLICATIONS: '/candidate/applications',
    APPLICATION_DETAIL: (id: string) => `/candidate/applications/${id}`,
    SAVED_JOBS: '/candidate/saved-jobs',
    JOB_ALERTS: '/candidate/job-alerts',
    VERIFICATION: '/candidate/verification',
    SETTINGS: '/candidate/settings',
    HELP: '/candidate/help',
    TICKET_DETAIL: (id: string) => `/candidate/help/${id}`,
  },
  EMPLOYER: {
    DASHBOARD: '/employer',
    ONBOARDING: '/employer/onboarding',
    PROFILE: '/employer/profile',
    POST_JOB: '/employer/jobs/new',
    MY_JOBS: '/employer/jobs',
    JOB_DETAIL: (id: string) => `/employer/jobs/${id}`,
    JOB_EDIT: (id: string) => `/employer/jobs/${id}/edit`,
    JOB_APPLICATIONS: (id: string) => `/employer/jobs/${id}/applications`,
    APPLICATIONS: '/employer/applications',
    APPLICATION_DETAIL: (id: string) => `/employer/applications/${id}`,
    CANDIDATES: '/employer/candidates',
    CANDIDATE_DETAIL: (id: string) => `/employer/candidates/${id}`,
    SAVED_CANDIDATES: '/employer/candidates/saved',
    ANALYTICS: '/employer/analytics',
    PROFILE_PREVIEW: '/employer/profile/preview',
    VERIFICATION: '/employer/verification',
    SETTINGS: '/employer/settings',
    HELP: '/employer/help',
    TICKET_DETAIL: (id: string) => `/employer/help/${id}`,
  },
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    JOBS: '/admin/jobs',
    JOB_DETAIL: (id: string) => `/admin/jobs/${id}`,
    VERIFICATIONS: '/admin/verifications',
    ANALYTICS: '/admin/analytics',
    AUDIT_LOGS: '/admin/audit-logs',
    REPORTS: '/admin/reports',
    SETTINGS: '/admin/settings',
    TICKETS: '/admin/tickets',
    TICKET_DETAIL: (id: string) => `/admin/tickets/${id}`,
    MODERATION: '/admin/moderation',
    APPLICATIONS: '/admin/applications',
    EMAIL_TEMPLATES: '/admin/email-templates',
  },
  SUPER_ADMIN: {
    DASHBOARD: '/super-admin',
    ADMINS: '/super-admin/admins',
    ADMIN_DETAIL: (id: string) => `/super-admin/admins/${id}`,
    USERS: '/super-admin/users',
    USER_DETAIL: (id: string) => `/super-admin/users/${id}`,
    JOBS: '/super-admin/jobs',
    JOB_DETAIL: (id: string) => `/super-admin/jobs/${id}`,
    JOB_EDIT: (id: string) => `/super-admin/jobs/${id}/edit`,
    ANALYTICS: '/super-admin/analytics',
    FEATURE_FLAGS: '/super-admin/feature-flags',
    CONFIG: '/super-admin/config',
    TICKETS: '/super-admin/tickets',
    SETTINGS: '/super-admin/settings',
  },
  PORTAL: {
    LOGIN: '/portal/login',
  },
  NOTIFICATIONS: '/notifications',
} as const;

export const PUBLIC_ROUTES = [
  ROUTES.PUBLIC.HOME,
  ROUTES.PUBLIC.ABOUT,
  ROUTES.PUBLIC.CONTACT,
  ROUTES.PUBLIC.HELP,
  ROUTES.PUBLIC.PRIVACY,
  ROUTES.PUBLIC.TERMS,
  ROUTES.PUBLIC.COOKIE_POLICY,
  ROUTES.PUBLIC.REFUND_POLICY,
  ROUTES.PUBLIC.ACCESSIBILITY,
  ROUTES.PUBLIC.DISCLAIMER,
];

export const AUTH_ROUTES = [
  ROUTES.AUTH.LOGIN,
  ROUTES.AUTH.REGISTER,
  ROUTES.AUTH.FORGOT_PASSWORD,
  ROUTES.AUTH.RESET_PASSWORD,
  ROUTES.AUTH.VERIFY_EMAIL,
  ROUTES.PORTAL.LOGIN,
];

export const ROLE_DASHBOARDS = {
  CANDIDATE: ROUTES.CANDIDATE.DASHBOARD,
  EMPLOYER: ROUTES.EMPLOYER.DASHBOARD,
  ADMIN: ROUTES.ADMIN.DASHBOARD,
  SUPER_ADMIN: ROUTES.SUPER_ADMIN.DASHBOARD,
} as const;
