/**
 * Auto-suggestion data for onboarding and profile forms.
 * Comprehensive lists based on Indian job market (Naukri/Indeed style).
 */

import { INDIAN_CITIES } from './indian-cities';

export const SKILL_SUGGESTIONS = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'Go',
  'Rust',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'Scala',
  'R',
  'MATLAB',
  'Dart',
  'Perl',
  'Lua',
  'Haskell',
  'Elixir',
  'Clojure',
  'F#',
  'Objective-C',
  'Assembly',
  'COBOL',
  'Fortran',
  'Shell Script',
  'Bash',
  'PowerShell',
  // Frontend
  'React',
  'Angular',
  'Vue.js',
  'Next.js',
  'Svelte',
  'HTML5',
  'CSS3',
  'Tailwind CSS',
  'Bootstrap',
  'SASS',
  'jQuery',
  'Redux',
  'Zustand',
  'GraphQL',
  'Nuxt.js',
  'Remix',
  'Astro',
  'SvelteKit',
  'Storybook',
  'Webpack',
  'Vite',
  'esbuild',
  'Rollup',
  'Turbopack',
  'Material UI',
  'Chakra UI',
  'Ant Design',
  'Radix UI',
  'Shadcn UI',
  'Framer Motion',
  'Three.js',
  'D3.js',
  'Chart.js',
  // Backend
  'Node.js',
  'Express.js',
  'Django',
  'Flask',
  'Spring Boot',
  'ASP.NET',
  'FastAPI',
  'Ruby on Rails',
  'Laravel',
  'NestJS',
  'Gin',
  'Fiber',
  'Actix',
  'Phoenix',
  'Hono',
  'Koa',
  'Fastify',
  'Strapi',
  'Prisma',
  'Drizzle',
  'tRPC',
  // Database
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Elasticsearch',
  'DynamoDB',
  'Cassandra',
  'Oracle',
  'SQL Server',
  'Firebase',
  'Supabase',
  'CockroachDB',
  'PlanetScale',
  'Neo4j',
  'InfluxDB',
  'TimescaleDB',
  'MariaDB',
  'SQLite',
  'Pinecone',
  'Weaviate',
  'Qdrant',
  // Cloud & DevOps
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'Terraform',
  'Jenkins',
  'CI/CD',
  'GitHub Actions',
  'Linux',
  'Nginx',
  'Apache',
  'Ansible',
  'Pulumi',
  'CloudFormation',
  'Helm',
  'ArgoCD',
  'GitLab CI',
  'CircleCI',
  'Travis CI',
  'Datadog',
  'Grafana',
  'Prometheus',
  'New Relic',
  'PagerDuty',
  'Vault',
  'Consul',
  'Istio',
  'Envoy',
  'DigitalOcean',
  'Vercel',
  'Netlify',
  'Cloudflare',
  // Mobile
  'React Native',
  'Flutter',
  'iOS Development',
  'Android Development',
  'SwiftUI',
  'Jetpack Compose',
  'Expo',
  'Capacitor',
  'Ionic',
  'Xamarin',
  'MAUI',
  'KMM (Kotlin Multiplatform)',
  // Data & AI
  'Machine Learning',
  'Deep Learning',
  'Natural Language Processing',
  'Computer Vision',
  'TensorFlow',
  'PyTorch',
  'Data Science',
  'Data Analysis',
  'Pandas',
  'NumPy',
  'Tableau',
  'Power BI',
  'Apache Spark',
  'Hadoop',
  'ETL',
  'Data Engineering',
  'LangChain',
  'LlamaIndex',
  'OpenAI API',
  'Hugging Face',
  'scikit-learn',
  'Keras',
  'XGBoost',
  'LightGBM',
  'Apache Kafka',
  'Apache Airflow',
  'dbt',
  'Snowflake',
  'Databricks',
  'Looker',
  'Metabase',
  'Superset',
  'MLflow',
  'Kubeflow',
  'Ray',
  'Weights & Biases',
  'Generative AI',
  'Prompt Engineering',
  'RAG',
  // Design
  'Figma',
  'Adobe XD',
  'Sketch',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'UI/UX Design',
  'Wireframing',
  'Prototyping',
  'Design Systems',
  'Adobe After Effects',
  'Adobe Premiere Pro',
  'Canva',
  'InVision',
  'Zeplin',
  'Abstract',
  'Principle',
  'Lottie',
  // Testing
  'Jest',
  'Selenium',
  'Cypress',
  'Playwright',
  'JUnit',
  'Postman',
  'API Testing',
  'Performance Testing',
  'Load Testing',
  'Vitest',
  'Mocha',
  'Chai',
  'TestNG',
  'Appium',
  'k6',
  'JMeter',
  'Gatling',
  'Robot Framework',
  'Cucumber',
  'BDD',
  'TDD',
  // Management & Soft Skills
  'Project Management',
  'Agile',
  'Scrum',
  'JIRA',
  'Confluence',
  'Team Leadership',
  'Communication',
  'Problem Solving',
  'Critical Thinking',
  'Kanban',
  'Lean',
  'OKRs',
  'Stakeholder Management',
  'Risk Management',
  'Change Management',
  'Strategic Planning',
  'Negotiation',
  'Monday.com',
  'Asana',
  'Trello',
  'Notion',
  'Linear',
  'ClickUp',
  'Basecamp',
  // Others
  'REST API',
  'Microservices',
  'System Design',
  'DSA',
  'OOP',
  'Git',
  'Blockchain',
  'Cybersecurity',
  'SEO',
  'Digital Marketing',
  'Content Writing',
  'Copywriting',
  'Sales',
  'Business Development',
  'Customer Service',
  'Financial Analysis',
  'Accounting',
  'Excel',
  'SAP',
  'Salesforce',
  'HubSpot',
  'Zoho',
  'Tally',
  'AutoCAD',
  'SolidWorks',
  'CATIA',
  'Solidity',
  'Web3.js',
  'Ethers.js',
  'IPFS',
  'RabbitMQ',
  'gRPC',
  'Protocol Buffers',
  'WebSocket',
  'OAuth',
  'JWT',
  'ServiceNow',
  'Workday',
  'Oracle ERP',
  'SAP HANA',
  'Dynamics 365',
  'Zendesk',
  'Freshdesk',
  'Intercom',
  'Google Ads',
  'Meta Ads',
  'Mailchimp',
  'SendGrid',
  'Twilio',
  'Stripe',
  'Razorpay',
  'Unreal Engine',
  'Unity',
  'Blender',
  'Maya',
  'Cinema 4D',
  'ANSYS',
  'CREO',
  'PTC Windchill',
  'OpenCV',
  'ONNX',
  'Feature Store',
  'Vector DB',
  'Fine-tuning',
  'Stable Diffusion',
  'GPT',
  'BERT',
  'Transformer Models',
  'Reinforcement Learning',
  'GANs',
  'Diffusion Models',
  'Model Quantization',
  'TensorRT',
  'CUDA',
  'JAX',
  'Caffe',
  'MXNet',
  'spaCy',
  'NLTK',
  'Gensim',
  'FastText',
  'SentenceTransformers',
  'LabelStudio',
  'Prodigy',
  'DVC',
  'BentoML',
  'Seldon',
  'TFX',
  'Feature Engineering',
  'Model Serving',
  'Edge AI',
  'TinyML',
  'AutoML',
  'Neural Architecture Search',
  'Federated Learning',
  'Knowledge Distillation',
  'Hive',
  'Presto',
  'Trino',
  'Dagster',
  'Prefect',
  'Fivetran',
  'Stitch',
  'Informatica',
  'Talend',
  'Delta Lake',
  'Apache Iceberg',
  'Data Lakehouse',
  'Star Schema',
  'Data Vault',
  'ELT',
  'Apache Flink',
  'Apache Beam',
  'Apache Hudi',
  'Apache Druid',
  'Apache Pinot',
  'Apache NiFi',
  'Apache Sqoop',
  'Apache Flume',
  'StreamSets',
  'Matillion',
  'Airbyte',
  'Great Expectations',
  'Monte Carlo',
  'Soda',
  'Apache Atlas',
  'OpenMetadata',
  'DataHub',
  'Amundsen',
  'AWS Lambda',
  'AWS ECS',
  'AWS EKS',
  'AWS S3',
  'AWS RDS',
  'AWS DynamoDB',
  'AWS SQS',
  'AWS SNS',
  'AWS CloudFront',
  'AWS Route 53',
  'AWS Glue',
  'AWS Redshift',
  'AWS Kinesis',
  'AWS Step Functions',
  'AWS SageMaker',
  'AWS Bedrock',
  'AWS CDK',
  'Azure Functions',
  'Azure DevOps',
  'Azure AD',
  'Azure Cosmos DB',
  'Azure Synapse',
  'Azure Data Factory',
  'Azure Event Hubs',
  'Azure Service Bus',
  'Azure Cognitive Services',
  'Azure OpenAI Service',
  'GCP Cloud Run',
  'GCP Dataflow',
  'GCP Vertex AI',
  'GCP BigQuery',
  'GCP Dataproc',
  'GCP Cloud Functions',
  'GCP Spanner',
  'Crossplane',
  'OpenTofu',
  'Linkerd',
  'FluxCD',
  'Spinnaker',
  'Tekton',
  'Kustomize',
  'Chef',
  'Puppet',
  'SaltStack',
  'Vagrant',
  'Packer',
  'Buildkite',
  'Drone CI',
  'Woodpecker CI',
  'GoCD',
  'Concourse',
  'Argo Workflows',
  'Argo Events',
  'Argo Rollouts',
  'Thanos',
  'Cortex',
  'Mimir',
  'Loki',
  'Tempo',
  'OpenTelemetry',
  'Jaeger',
  'Zipkin',
  'Sentry',
  'Elastic APM',
  'Dynatrace',
  'Splunk',
  'ELK Stack',
  'Fluentd',
  'Fluent Bit',
  'Vector',
  'Logstash',
  'Kibana',
  'Checkov',
  'Terraform Sentinel',
  'Falco',
  'Trivy',
  'Aqua Security',
  'Snyk Container',
  'SonarQube',
  'Nexus',
  'Artifactory',
  'Harbor',
  'Backstage',
  'Port',
  'Kratix',
  'Core Data',
  'Room DB',
  'Firebase Analytics',
  'App Store Optimization',
  'Deep Linking',
  'Realm',
  'SQLDelight',
  'Fastlane',
  'CocoaPods',
  'Swift Package Manager',
  'Gradle',
  'ProGuard',
  'Detox',
  'Maestro',
  'App Distribution',
  'TestFlight',
  'Play Console',
  'App Clips',
  'Android Auto',
  'WatchOS',
  'ARKit',
  'ARCore',
  'Core ML',
  'TensorFlow Lite',
  'MediaPipe',
  'Storybook Testing',
  'Accessibility Testing',
  'Chaos Engineering',
  'Locust',
  'Artillery',
  'WireMock',
  'MockServer',
  'Testcontainers',
  'ArchUnit',
  'Mutation Testing',
  'Visual Regression Testing',
  'Percy',
  'Chromatic',
  'BackstopJS',
  'Lighthouse CI',
  'Axe',
  'WAVE',
  'Karate DSL',
  'RestAssured',
  'SuperTest',
  'Nock',
  'Faker.js',
  'Factory Bot',
  'Hypothesis',
  'Snapshot Testing',
  'Integration Testing',
  'Contract Testing',
  'Smoke Testing',
  'Regression Testing',
  'Exploratory Testing',
  'SAP FICO',
  'SAP MM',
  'SAP SD',
  'SAP ABAP',
  'SAP Basis',
  'SAP BW',
  'SAP CRM',
  'SAP PP',
  'SAP QM',
  'SAP WM',
  'SAP PM',
  'SAP HCM',
  'SAP SuccessFactors',
  'Oracle EBS',
  'Oracle Fusion',
  'Oracle PeopleSoft',
  'Oracle JD Edwards',
  'Oracle Siebel',
  'SuccessFactors',
  'Marketo',
  'Pardot',
  'Eloqua',
  'Dynamics 365 Finance',
  'Dynamics 365 Sales',
  'Dynamics 365 CE',
  'NetSuite',
  'Sage',
  'Epicor',
  'Infor',
  'IFS',
  'Framer',
  'ProtoPie',
  'Marvel',
  'Balsamiq',
  'Axure',
  'Miro',
  'FigJam',
  'Whimsical',
  'Lucidchart',
  'InDesign',
  'Lightroom',
  '3ds Max',
  'ZBrush',
  'Houdini',
  'DaVinci Resolve',
  'Final Cut Pro',
  'Procreate',
  'Affinity Designer',
  'Affinity Photo',
  'CorelDRAW',
  'Webflow',
  'Spline',
  'Rive',
  'TiDB',
  'Vitess',
  'ScyllaDB',
  'HBase',
  'ArangoDB',
  'Couchbase',
  'QuestDB',
  'Milvus',
  'Chroma',
  'ClickHouse',
  'Apache Doris',
  'YugabyteDB',
  'FaunaDB',
  'SurrealDB',
  'EdgeDB',
  'Neon',
  'Turso',
  'Xata',
  'RethinkDB',
  'ArcticDB',
  'DuckDB',
  'Polars',
  'OWASP',
  'SAST',
  'DAST',
  'IAST',
  'SCA',
  'Snyk',
  'Checkmarx',
  'Veracode',
  'HashiCorp Vault',
  'AWS IAM',
  'Okta',
  'Auth0',
  'Keycloak',
  'Zero Trust',
  'mTLS',
  'Sigstore',
  'Cosign',
  'SBOM',
  'CycloneDX',
  'Semgrep',
  'CodeQL',
  'Dependabot',
  'Renovate',
  'SIEM',
  'SOAR',
  'EDR',
  'XDR',
  'WAF',
  'DDoS Mitigation',
  'Penetration Testing',
  'Bug Bounty',
  'Threat Modeling',
  'Incident Response',
  'Digital Forensics',
  'LinkedIn Ads',
  'Google Analytics 4',
  'Mixpanel',
  'Amplitude',
  'Segment',
  'Braze',
  'CleverTap',
  'MoEngage',
  'WebEngage',
  'Leanplum',
  'Optimizely',
  'VWO',
  'LaunchDarkly',
  'Hotjar',
  'Heap',
  'FullStory',
  'PostHog',
  'Rudderstack',
  'mParticle',
  'Appsflyer',
  'Branch',
  'Adjust',
  'SEM',
  'Content Marketing',
  'Growth Hacking',
  'Conversion Optimization',
  'Marketing Automation',
  'CRM Strategy',
  'Affiliate Marketing',
  'Influencer Marketing',
  'Email Marketing',
  'Push Notifications',
  'QuickBooks',
  'Oracle Financials',
  'Bloomberg Terminal',
  'Reuters Eikon',
  'IFRS',
  'GAAP',
  'Indian GAAP',
  'GST',
  'Income Tax',
  'Transfer Pricing',
  'Treasury Management',
  'Actuarial Science',
  'Derivatives',
  'Fixed Income',
  'Equity Analysis',
  'Portfolio Management',
  'Fund Accounting',
  'Reconciliation',
  'SWIFT Messaging',
  'Trade Finance',
  'KYC',
  'Basel III',
  'FEMA',
  'RBI Guidelines',
  'Forex',
  'Commodity Trading',
  'Algorithmic Trading',
  'Quantitative Finance',
  'Financial Modeling',
  'Valuation',
  'IPO',
  'Venture Capital Analysis',
  'Credit Risk',
  'Market Risk',
  'Operational Risk',
] as const;

export const INDUSTRY_SUGGESTIONS = [
  'Information Technology',
  'Software Development',
  'E-Commerce',
  'FinTech',
  'EdTech',
  'HealthTech',
  'Banking & Financial Services',
  'Insurance',
  'Management Consulting',
  'KPO/Research',
  'BPO/Call Center',
  'Advertising & Marketing',
  'Media & Entertainment',
  'Telecom',
  'Manufacturing',
  'Automobile',
  'Aerospace & Defence',
  'Oil & Gas',
  'Mining',
  'Pharmaceuticals',
  'Healthcare',
  'Biotechnology',
  'Medical Devices',
  'Real Estate',
  'Construction',
  'Architecture & Interior Design',
  'Retail',
  'FMCG',
  'Consumer Electronics',
  'Fashion & Lifestyle',
  'Education & Training',
  'Travel & Tourism',
  'Hospitality',
  'Government & Public Sector',
  'NGO/Social Services',
  'Legal',
  'Logistics & Supply Chain',
  'Shipping & Marine',
  'Aviation',
  'Agriculture & Forestry',
  'Food Processing',
  'Textiles',
  'Power & Energy',
  'Renewable Energy',
  'Chemicals',
  'Recruitment & Staffing',
  'Facility Management',
  'Security Services',
  'Sports & Fitness',
  'Gaming',
  'Blockchain & Cryptocurrency',
  'PropTech',
  'CleanTech',
  'SpaceTech',
  'LegalTech',
  'HRTech',
  'FoodTech',
  'Quick Commerce',
  'D2C Brands',
  'SaaS',
  'Cloud Computing',
  'Robotics & Automation',
  'Electric Vehicles',
  'Drones & UAV',
  'Semiconductors',
  'Internet of Things',
  'AR/VR/Metaverse',
  'Social Media',
  'Content & Publishing',
  'OTT & Streaming',
  'Animation & VFX',
  'Market Research',
  'Data Analytics',
  'Environmental Services',
  'Waste Management',
  'Water & Sanitation',
  'Packaging',
  'Printing',
  'Gems & Jewellery',
  'Leather',
  'Cement',
  'Steel',
  'Paper & Pulp',
  'Glass & Ceramics',
  'Railways',
  'Ports & Warehousing',
  'Urban Planning',
  'Venture Capital & PE',
  'Wealth Management',
  'Stock Broking',
] as const;

export const DEPARTMENT_SUGGESTIONS = [
  'Engineering - Software',
  'Engineering - Hardware',
  'Engineering - Mechanical',
  'Engineering - Civil',
  'Engineering - Electrical',
  'Engineering - Chemical',
  'Data Science & Analytics',
  'Artificial Intelligence & ML',
  'Product Management',
  'Design - UI/UX',
  'Design - Graphic',
  'Quality Assurance & Testing',
  'DevOps & Infrastructure',
  'Information Security',
  'IT & Networking',
  'Sales & Business Development',
  'Marketing & Communications',
  'Digital Marketing & SEO',
  'Content & Creative',
  'Human Resources',
  'Talent Acquisition',
  'Learning & Development',
  'Finance & Accounting',
  'Legal & Compliance',
  'Operations',
  'Customer Success',
  'Customer Support',
  'Technical Support',
  'Supply Chain & Logistics',
  'Procurement',
  'Administration',
  'Research & Development',
  'Strategy & Consulting',
  'Project Management',
  'Business Analysis',
] as const;

export const ROLE_CATEGORY_SUGGESTIONS = [
  'Software Developer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'Mobile Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Site Reliability Engineer',
  'Data Scientist',
  'Data Analyst',
  'Data Engineer',
  'ML Engineer',
  'AI Researcher',
  'Product Manager',
  'Project Manager',
  'Scrum Master',
  'Business Analyst',
  'UI/UX Designer',
  'Graphic Designer',
  'Product Designer',
  'UX Researcher',
  'QA Engineer',
  'SDET',
  'Test Lead',
  'Automation Engineer',
  'Technical Lead',
  'Engineering Manager',
  'VP of Engineering',
  'CTO',
  'Solutions Architect',
  'Enterprise Architect',
  'Technical Architect',
  'Sales Executive',
  'Account Manager',
  'Business Development Manager',
  'Marketing Manager',
  'Digital Marketing Specialist',
  'SEO Specialist',
  'Content Writer',
  'HR Manager',
  'Recruiter',
  'Talent Acquisition Specialist',
  'Finance Manager',
  'Chartered Accountant',
  'Financial Analyst',
  'Operations Manager',
  'Customer Success Manager',
  'Support Engineer',
  'Consultant',
  'Analyst',
  'Researcher',
  'Intern',
  // Extended roles
  'Platform Engineer',
  'Security Engineer',
  'AppSec Engineer',
  'Penetration Tester',
  'Staff Engineer',
  'Principal Engineer',
  'Distinguished Engineer',
  'Fellow',
  'Developer Relations (DevRel)',
  'Developer Advocate',
  'Technical Writer',
  'Technical Program Manager',
  'Cloud Architect',
  'Database Administrator',
  'Network Engineer',
  'Systems Administrator',
  'Embedded Systems Engineer',
  'Firmware Engineer',
  'Hardware Engineer',
  'VLSI Design Engineer',
  'Game Developer',
  'Game Designer',
  'AR/VR Developer',
  'Blockchain Developer',
  'AI/ML Ops Engineer',
  'NLP Engineer',
  'Computer Vision Engineer',
  'Robotics Engineer',
  'Growth Hacker',
  'Performance Marketer',
  'Brand Manager',
  'Social Media Manager',
  'Content Strategist',
  'Communications Manager',
  'PR Manager',
  'Copywriter',
  'Chief Product Officer',
  'Chief Data Officer',
  'Chief Information Officer',
  'Chief Revenue Officer',
  'VP of Product',
  'VP of Design',
  'VP of Sales',
  'VP of Marketing',
  'Supply Chain Manager',
  'Procurement Manager',
  'Warehouse Manager',
  'Logistics Coordinator',
  'Compliance Officer',
  'Risk Analyst',
  'Internal Auditor',
  'Legal Counsel',
  'Investment Banker',
  'Equity Research Analyst',
  'Credit Analyst',
  'Treasury Manager',
  'Instructional Designer',
  'Learning Experience Designer',
  'Training Manager',
  'Talent Development Specialist',
  'Compensation & Benefits Analyst',
  'HRBP',
  'Solutions Engineer',
  'Pre-Sales Consultant',
  'Customer Engineer',
  'Implementation Specialist',
] as const;

export const LOCATION_SUGGESTIONS: readonly string[] = INDIAN_CITIES;

export const INSTITUTION_SUGGESTIONS = [
  // IITs
  'IIT Bombay',
  'IIT Delhi',
  'IIT Madras',
  'IIT Kanpur',
  'IIT Kharagpur',
  'IIT Roorkee',
  'IIT Guwahati',
  'IIT Hyderabad',
  'IIT BHU',
  'IIT Indore',
  'IIT Gandhinagar',
  'IIT Patna',
  'IIT Jodhpur',
  'IIT Mandi',
  'IIT Bhubaneswar',
  'IIT Tirupati',
  'IIT Dhanbad (ISM)',
  'IIT Palakkad',
  'IIT Dharwad',
  'IIT Bhilai',
  // IIMs
  'IIM Ahmedabad',
  'IIM Bangalore',
  'IIM Calcutta',
  'IIM Lucknow',
  'IIM Indore',
  'IIM Kozhikode',
  'IIM Shillong',
  'IIM Ranchi',
  'IIM Raipur',
  'IIM Tiruchirappalli',
  'IIM Udaipur',
  'IIM Kashipur',
  'IIM Nagpur',
  'IIM Rohtak',
  'IIM Bodh Gaya',
  // NITs
  'NIT Trichy',
  'NIT Warangal',
  'NIT Surathkal',
  'NIT Calicut',
  'NIT Rourkela',
  'NIT Allahabad',
  'NIT Jaipur',
  'NIT Nagpur',
  'NIT Kurukshetra',
  'NIT Durgapur',
  'NIT Bhopal',
  'NIT Srinagar',
  'NIT Silchar',
  'NIT Hamirpur',
  'NIT Jalandhar',
  // IIITs
  'IIIT Hyderabad',
  'IIIT Bangalore',
  'IIIT Allahabad',
  'IIIT Delhi',
  'IIIT Gwalior',
  'IIIT Jabalpur',
  'IIIT Kancheepuram',
  'IIIT Sri City',
  'IIIT Lucknow',
  // IISERs
  'IISER Pune',
  'IISER Kolkata',
  'IISER Mohali',
  'IISER Bhopal',
  'IISER Thiruvananthapuram',
  // BITS & ISI
  'BITS Pilani',
  'BITS Hyderabad',
  'BITS Goa',
  'ISI Kolkata',
  'ISI Delhi',
  'ISI Bangalore',
  // Central Universities
  'Delhi University',
  'JNU (Jawaharlal Nehru University)',
  'BHU (Banaras Hindu University)',
  'Aligarh Muslim University',
  'Jamia Millia Islamia',
  'Hyderabad Central University',
  'Pondicherry University',
  'Visva-Bharati',
  'Tezpur University',
  // State Universities
  'Anna University',
  'Jadavpur University',
  'Pune University (SPPU)',
  'Mumbai University',
  'Osmania University',
  'Calcutta University',
  'Madras University',
  'Bangalore University',
  'Gujarat University',
  'Rajasthan University',
  'Lucknow University',
  'Patna University',
  'Andhra University',
  'Kerala University',
  'Mysore University',
  'Gauhati University',
  // Deemed & Private
  'VIT Vellore',
  'SRM University',
  'Manipal Academy (MAHE)',
  'Amity University',
  'Christ University',
  'Symbiosis International',
  'NMIMS',
  'XLRI Jamshedpur',
  'Thapar University',
  'Shiv Nadar University',
  'Ashoka University',
  'Plaksha University',
  'Lovely Professional University',
  'Chandigarh University',
  'Jain University',
  'KIIT Bhubaneswar',
  'Vellore Institute of Technology (VIT AP)',
  'SRM AP',
  // Engineering Colleges
  'PSG College of Technology',
  'BMS College of Engineering',
  'RVCE Bangalore',
  'PES University',
  'DTU Delhi',
  'NSUT Delhi',
  'IIITD&M Kancheepuram',
  'College of Engineering Pune (COEP)',
  'Netaji Subhas University of Technology',
  'Jadavpur Engineering',
  'MNNIT Allahabad',
  // Management & Business
  'ISB Hyderabad',
  'FMS Delhi',
  'SPJIMR Mumbai',
  'MDI Gurgaon',
  'IIM Sambalpur',
  'IMT Ghaziabad',
  'TAPMI Manipal',
  'Great Lakes Chennai',
  'SIBM Pune',
  'SCMHRD Pune',
  // Medical & Law
  'AIIMS Delhi',
  'AIIMS Jodhpur',
  'JIPMER',
  'CMC Vellore',
  'KEM Hospital Mumbai',
  'NLSIU Bangalore',
  'NALSAR Hyderabad',
  'NLU Delhi',
  'NLU Jodhpur',
  'NUJS Kolkata',
  // Distance & Open
  'IGNOU',
  'Sikkim Manipal Distance',
  'Annamalai University Distance',
  'IIT Goa',
  'IIT Jammu',
  'IIT Ropar',
  'IIM Visakhapatnam',
  'IIM Amritsar',
  'IIM Jammu',
  'IIM Sirmaur',
  'IIM Mumbai',
  'NIT Patna',
  'NIT Raipur',
  'NIT Agartala',
  'NIT Arunachal Pradesh',
  'NIT Delhi',
  'NIT Goa',
  'NIT Manipur',
  'NIT Meghalaya',
  'NIT Mizoram',
  'NIT Nagaland',
  'NIT Puducherry',
  'NIT Sikkim',
  'NIT Uttarakhand',
  'NIT Andhra Pradesh',
  'NIT Surat (SVNIT)',
  'NIT Jamshedpur',
  'NIT Karnataka (NITK)',
  'AIIMS Bhopal',
  'AIIMS Bhubaneswar',
  'AIIMS Patna',
  'AIIMS Raipur',
  'AIIMS Rishikesh',
  'AIIMS Nagpur',
  'AIIMS Mangalagiri',
  'AIIMS Gorakhpur',
  'AIIMS Kalyani',
  'AIIMS Bathinda',
  'AIIMS Deoghar',
  'AIIMS Bilaspur',
  'AIIMS Rajkot',
  'AIIMS Raebareli',
  'AIIMS Madurai',
  'NEHU (North Eastern Hill University)',
  'Mizoram University',
  'Nagaland University',
  'Tripura University',
  'Sikkim University',
  'Rajiv Gandhi University',
  'Mahatma Gandhi University',
  'Central University of Kerala',
  'Central University of Rajasthan',
  'Central University of Haryana',
  'Central University of Punjab',
  'Central University of Gujarat',
  'Central University of Tamil Nadu',
  'Central University of Karnataka',
  'Central University of Jharkhand',
  'Central University of Kashmir',
  'Central University of Odisha',
  'Babasaheb Bhimrao Ambedkar University',
  'Dr. Harisingh Gour University',
  'Hemvati Nandan Bahuguna Garhwal University',
  'Indira Gandhi National Tribal University',
  'Maulana Azad National Urdu University',
  'Azim Premji University',
  'OP Jindal Global University',
  'Shiv Nadar IoE',
  'DAIICT Gandhinagar',
  'Jaypee Institute of Information Technology',
  'Graphic Era University',
  'DIT University',
  'Chitkara University',
  'Bennett University',
  'Woxsen University',
  'FLAME University',
  'Krea University',
  'Srishti Manipal Institute',
  'UPES Dehradun',
  'Nirma University',
  'PDEU Gandhinagar',
  'DA-IICT',
  'LNMIIT Jaipur',
  'IIITDM Jabalpur',
  'ABV-IIITM Gwalior',
  'MS Ramaiah Institute of Technology',
  'RV College of Engineering',
  'BMS Institute of Technology',
  'Dayananda Sagar College of Engineering',
  'SSN College of Engineering',
  'CEG Anna University',
  'Thiagarajar College of Engineering',
  'Govt. College of Technology Coimbatore',
  'Kongu Engineering College',
  'Kumaraguru College of Technology',
  'Sri Sivasubramaniya Nadar College',
  'Mepco Schlenk Engineering College',
  'JNTU Hyderabad',
  'JNTU Kakinada',
  'JNTU Anantapur',
  'Calicut University',
  'Cochin University (CUSAT)',
  'Sri Venkateswara University',
  'Ranchi University',
  'Allahabad University',
  'Burdwan University',
  'North Bengal University',
  'Kalyani University',
  'Vidyasagar University',
  'Dibrugarh University',
  'Manipur University',
  'Sambalpur University',
  'Berhampur University',
  'Utkal University',
  'Ravenshaw University',
  'Savitribai Phule Pune University',
  'Dr. Babasaheb Ambedkar Marathwada University',
  'Shivaji University',
  'North Maharashtra University',
  'Solapur University',
  'Kurukshetra University',
  'Maharshi Dayanand University',
  'Guru Nanak Dev University',
  'Panjab University',
  'Himachal Pradesh University',
  'University of Jammu',
  'University of Kashmir',
  'Goa University',
  'Gujarat Technological University',
  'Saurashtra University',
  'MS University Baroda',
  'Sardar Patel University',
  'Mohanlal Sukhadia University',
  'Jai Narain Vyas University',
  'MDS University Ajmer',
  'Mahatma Gandhi Kashi Vidyapith',
  'DDU Gorakhpur University',
  'Chhatrapati Shahu Ji Maharaj University',
  'Bundelkhand University',
  'Awadhesh Pratap Singh University',
  'Barkatullah University',
  'Devi Ahilya University',
  'Rani Durgavati University',
  'Guru Ghasidas University',
  'Pt. Ravishankar Shukla University',
  'Nalanda University',
  'IISc Bangalore',
  'NLIU Bhopal',
  'GNLU Gandhinagar',
  'RGNUL Patiala',
  'NUSRL Ranchi',
  'CNLU Patna',
  'NUALS Kochi',
  'Chanakya National Law University',
  'DSNLU Visakhapatnam',
  'Tamil Nadu National Law University',
  'Maharashtra National Law University Mumbai',
  'Maharashtra National Law University Nagpur',
  'NITIE Mumbai (IIM Mumbai)',
  'IRMA Anand',
  'MICA Ahmedabad',
  'IIFT Delhi',
  'IIFT Kakinada',
  'LBSNAA Mussoorie',
  'Xavier Institute of Management Bhubaneswar',
  'Goa Institute of Management',
  'Narsee Monjee Institute of Management Studies',
  'Welingkar Institute',
  'KJ Somaiya Institute',
  'Jamnalal Bajaj Institute',
  'Prin. L.N. Welingkar Institute',
] as const;

export const DEGREE_SUGGESTIONS = [
  // Undergraduate
  'B.Tech',
  'B.E.',
  'B.Sc',
  'BCA',
  'BBA',
  'B.Com',
  'BA',
  'B.Arch',
  'B.Des',
  'B.Pharm',
  'B.Ed',
  'BFA',
  'BHM (Hotel Management)',
  'B.Voc',
  'BJMC (Journalism)',
  'BSW (Social Work)',
  'BMS (Management Studies)',
  'B.Stat',
  'B.Math',
  'BPA (Performing Arts)',
  'B.Lib',
  // Postgraduate
  'M.Tech',
  'M.E.',
  'M.Sc',
  'MCA',
  'MBA',
  'M.Com',
  'MA',
  'M.Arch',
  'M.Des',
  'M.Pharm',
  'PGDM',
  'PGDBA',
  'PGPM',
  'M.Phil',
  'M.Ed',
  'MFA',
  'MSW (Social Work)',
  'M.Stat',
  'M.Math',
  'MPA (Public Administration)',
  'M.Lib',
  // Doctoral
  'Ph.D.',
  'Post Doctoral',
  'D.Litt',
  'D.Sc',
  'DBA',
  // Professional
  'CA',
  'CS',
  'CMA',
  'CFA',
  'ICWA',
  'FRM',
  'ACCA',
  'LLB',
  'LLM',
  'Integrated LLB (5-year)',
  'MBBS',
  'MD',
  'MS',
  'BDS',
  'MDS',
  'BAMS',
  'BHMS',
  'BPT',
  'B.Sc Nursing',
  // Diploma & Certificate
  'Diploma',
  'ITI',
  'Polytechnic',
  'Advanced Diploma',
  'Post Graduate Diploma',
  'Certificate Course',
  'Executive Diploma',
  'Executive MBA',
  // Integrated
  'Integrated B.Tech + M.Tech (5-year)',
  'Integrated M.Sc (5-year)',
  'Dual Degree',
  // School
  '10th',
  '12th',
  'CBSE',
  'ICSE',
  'State Board',
  'IB',
  'IGCSE',
] as const;

export const FIELD_OF_STUDY_SUGGESTIONS = [
  // Engineering
  'Computer Science',
  'Information Technology',
  'Electronics & Communication',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Aerospace Engineering',
  'Biotechnology',
  'Biomedical Engineering',
  'Robotics Engineering',
  'Marine Engineering',
  'Petroleum Engineering',
  'Mining Engineering',
  'Metallurgical Engineering',
  'Industrial Engineering',
  'Production Engineering',
  'Instrumentation Engineering',
  'Automobile Engineering',
  'Textile Engineering',
  'Agricultural Engineering',
  'Mechatronics',
  'Nanotechnology',
  'Nuclear Engineering',
  'Environmental Engineering',
  // Science & Math
  'Data Science',
  'Artificial Intelligence',
  'Cybersecurity',
  'Mathematics',
  'Statistics',
  'Physics',
  'Chemistry',
  'Biology',
  'Actuarial Science',
  'Applied Mathematics',
  'Bioinformatics',
  'Computational Biology',
  'Geology',
  'Geophysics',
  'Astrophysics',
  'Material Science',
  'Polymer Science',
  // Business & Management
  'Business Administration',
  'Finance',
  'Marketing',
  'Human Resource Management',
  'Commerce',
  'Economics',
  'Accounting',
  'International Business',
  'Operations Management',
  'Supply Chain Management',
  'Entrepreneurship',
  'Business Analytics',
  'Sports Management',
  'Healthcare Management',
  'Hospitality Management',
  'Event Management',
  'Retail Management',
  'Rural Management',
  'Real Estate Management',
  // Humanities & Social Sciences
  'Law',
  'Political Science',
  'Psychology',
  'Sociology',
  'English Literature',
  'Hindi Literature',
  'History',
  'Philosophy',
  'Journalism & Mass Communication',
  'Public Relations',
  'Advertising',
  'Social Work',
  'Anthropology',
  'Geography',
  'Linguistics',
  'Education',
  // Design & Arts
  'Design',
  'Architecture',
  'Fine Arts',
  'Mass Communication',
  'Graphic Design',
  'Fashion Design',
  'Interior Design',
  'Animation & Multimedia',
  'Film Studies',
  'Performing Arts',
  'Music',
  'Visual Communication',
  // Medical & Health
  'Pharmacy',
  'Medicine',
  'Nursing',
  'Public Health',
  'Dentistry',
  'Physiotherapy',
  'Veterinary Science',
  'Ayurveda',
  'Homeopathy',
  'Nutrition & Dietetics',
  'Occupational Therapy',
  'Optometry',
  // Agriculture & Environment
  'Environmental Science',
  'Agricultural Science',
  'Food Technology',
  'Forestry',
  'Horticulture',
  'Fisheries Science',
  'Dairy Technology',
  'Food Science',
] as const;

export const COMPANY_NAME_SUGGESTIONS = [
  // Major IT Services
  'TCS',
  'Infosys',
  'Wipro',
  'HCL Technologies',
  'Tech Mahindra',
  'Cognizant',
  'Accenture',
  'Capgemini',
  'IBM',
  'Oracle',
  'LTIMindtree',
  'Mphasis',
  'Persistent Systems',
  'Coforge',
  'Hexaware',
  'Zensar Technologies',
  'NIIT Technologies',
  'Cyient',
  'Birlasoft',
  'L&T Infotech',
  'Mindtree',
  'iGate',
  'Syntel',
  'Virtusa',
  'UST',
  // Global Big Tech
  'Google',
  'Microsoft',
  'Amazon',
  'Meta',
  'Apple',
  'Netflix',
  'Uber',
  'Airbnb',
  'Spotify',
  'Salesforce',
  'Adobe',
  'VMware',
  'Cisco',
  'Dell Technologies',
  'HP',
  'Twitter/X',
  'LinkedIn',
  'Snap',
  'Pinterest',
  'Shopify',
  // Indian Startups & Unicorns
  'Flipkart',
  'Swiggy',
  'Zomato',
  'Paytm',
  'Razorpay',
  'Ola',
  'PhonePe',
  'CRED',
  'Dream11',
  "Byju's",
  'Zerodha',
  'Groww',
  'Meesho',
  'Nykaa',
  'UrbanCompany',
  'Delhivery',
  'Pine Labs',
  'Postman',
  'Freshworks',
  'Zoho',
  'Chargebee',
  'BrowserStack',
  'Unacademy',
  'upGrad',
  'Vedantu',
  'Lenskart',
  'CarDekho',
  'Cars24',
  'OYO Rooms',
  'MakeMyTrip',
  'PolicyBazaar',
  'Pharmeasy',
  '1mg',
  'Practo',
  'CureFit',
  'Dunzo',
  'BigBasket',
  'BlinkIt',
  'Rapido',
  'Ather Energy',
  'Juspay',
  'Simpl',
  'Slice',
  'Jupiter',
  'Fi Money',
  'ShareChat',
  'Moj',
  'Koo',
  'Dailyhunt',
  'InMobi',
  // Indian Conglomerates
  'Reliance Industries',
  'Tata Group',
  'Mahindra Group',
  'Adani Group',
  'Godrej Group',
  'Aditya Birla Group',
  'ITC',
  'Bajaj Group',
  'Larsen & Toubro',
  'Vedanta',
  'JSW Group',
  'Hinduja Group',
  'TVS Group',
  'RPG Group',
  'Hero Group',
  // Banking & Financial
  'HDFC Bank',
  'ICICI Bank',
  'SBI',
  'Kotak Mahindra',
  'Axis Bank',
  'Yes Bank',
  'IndusInd Bank',
  'Federal Bank',
  'Bandhan Bank',
  'IDFC First Bank',
  'RBI',
  'SEBI',
  'NSE',
  'BSE',
  'CRISIL',
  'LIC',
  'SBI Life',
  'ICICI Prudential',
  'HDFC Life',
  'Bajaj Allianz',
  // Consulting & Professional Services
  'Deloitte',
  'EY',
  'PwC',
  'KPMG',
  'McKinsey',
  'BCG',
  'Bain & Company',
  'Oliver Wyman',
  'Alvarez & Marsal',
  'ZS Associates',
  // Product Companies
  'Atlassian',
  'SAP',
  'ServiceNow',
  'Twilio',
  'Stripe',
  'GitHub',
  'GitLab',
  'Confluent',
  'DataDog',
  'Snowflake',
  'Palantir',
  'Databricks',
  'HashiCorp',
  'Elastic',
  'MongoDB',
  // Semiconductor & Hardware
  'Samsung',
  'LG',
  'Qualcomm',
  'Intel',
  'NVIDIA',
  'AMD',
  'Broadcom',
  'Texas Instruments',
  'MediaTek',
  'ARM',
  'TSMC',
  'SK Hynix',
  'Micron',
  'Western Digital',
  'Foxconn',
  // Government & PSU
  'ISRO',
  'DRDO',
  'BARC',
  'HAL',
  'BEL',
  'BHEL',
  'ONGC',
  'NTPC',
  'Indian Oil',
  'GAIL',
  'SAIL',
  'Coal India',
  'Power Grid',
  'BSNL',
  'Indian Railways',
  'Mastek',
  'KPIT Technologies',
  'Sasken Technologies',
  'Sonata Software',
  'Happiest Minds',
  'Newgen Software',
  'Intellect Design Arena',
  'Ramco Systems',
  'Kellton Tech',
  'Nucleus Software',
  'NIIT Ltd',
  'Quick Heal Technologies',
  'Rolta India',
  'Subex',
  'Tanla Platforms',
  '63 Moons Technologies',
  'BharatPe',
  'boAt',
  'Sugar Cosmetics',
  'Mamaearth',
  'Udaan',
  'Physics Wallah',
  'Moglix',
  'OfBusiness',
  'ElasticRun',
  'CoinSwitch',
  'CoinDCX',
  'Hasura',
  'Druva',
  'Icertis',
  'Whatfix',
  'Darwinbox',
  'Leena AI',
  'Yellow.ai',
  'MindTickle',
  'Innovaccer',
  'Zenoti',
  'CleverTap',
  'WebEngage',
  'MoEngage',
  'Capillary Technologies',
  'Haptik',
  'Vernacular.ai',
  'Observe.AI',
  'Rupeek',
  'Zetwerk',
  'Spinny',
  'Park+',
  'Fashinza',
  'DealShare',
  'Apna',
  'Classplus',
  'Eruditus',
  'Great Learning',
  'Simplilearn',
  'Scaler Academy',
  'Coding Ninjas',
  'InterviewBit',
  'Navi Technologies',
  'Open Financial Technologies',
  'Perfios',
  'KreditBee',
  'MoneyTap',
  'ZestMoney',
  'LazyPay',
  'Khatabook',
  'OkCredit',
  'Vyapar',
  'myBillBook',
  'Shiprocket',
  'Ecom Express',
  'XpressBees',
  'Shadowfax',
  'Porter',
  'BlackBuck',
  'State Bank of India',
  'Bank of Baroda',
  'Punjab National Bank',
  'Canara Bank',
  'Union Bank of India',
  'Indian Bank',
  'Central Bank of India',
  'Bank of India',
  'IDBI Bank',
  'South Indian Bank',
  'Karur Vysya Bank',
  'City Union Bank',
  'AU Small Finance Bank',
  'Equitas Small Finance Bank',
  'Ujjivan Small Finance Bank',
  'Bajaj Finance',
  'Bajaj Finserv',
  'Shriram Finance',
  'Muthoot Finance',
  'Manappuram Finance',
  'Mahindra Finance',
  'Tata Capital',
  'Aditya Birla Capital',
  'Max Life Insurance',
  'Tata AIA Life Insurance',
  'ICICI Lombard',
  'New India Assurance',
  'United India Insurance',
  'Star Health Insurance',
  'Care Health Insurance',
  'Niva Bupa',
  'Hindustan Unilever',
  'Nestle India',
  'Dabur India',
  'Marico',
  'Godrej Consumer Products',
  'Britannia Industries',
  'Parle Products',
  'Amul (GCMMF)',
  'Haldirams',
  'Mother Dairy',
  'Adani Wilmar',
  'Tata Consumer Products',
  'Patanjali Ayurved',
  'Emami',
  'Colgate-Palmolive India',
  'Procter & Gamble India',
  'Reckitt India',
  'Johnson & Johnson India',
  'Mondelez India',
  'PepsiCo India',
  'Coca-Cola India',
  'Perfetti Van Melle India',
  'Mars India',
  'Ferrero India',
  'Sun Pharmaceutical',
  'Cipla',
  'Lupin',
  'Aurobindo Pharma',
  'Divis Laboratories',
  'Biocon',
  'Glenmark Pharmaceuticals',
  'Torrent Pharmaceuticals',
  'Zydus Lifesciences',
  'Alkem Laboratories',
  'Mankind Pharma',
  'Natco Pharma',
  'Laurus Labs',
  'Granules India',
  'Ipca Laboratories',
  'Ajanta Pharma',
  'Aarti Drugs',
  'Apollo Hospitals',
  'Fortis Healthcare',
  'Max Healthcare',
  'Narayana Health',
  'Manipal Hospitals',
  'Aster DM Healthcare',
  'HCG Oncology',
  'Medanta',
  'Kokilaben Dhirubhai Ambani Hospital',
  'Thyrocare',
  'Dr Lal PathLabs',
  'Metropolis Healthcare',
  'SRL Diagnostics',
  'Tata Motors',
  'Maruti Suzuki',
  'Mahindra & Mahindra',
  'Bajaj Auto',
  'Hero MotoCorp',
  'TVS Motor Company',
  'Ashok Leyland',
  'Eicher Motors (Royal Enfield)',
  'Force Motors',
  'Tata Steel',
  'JSW Steel',
  'Hindalco Industries',
  'Grasim Industries',
  'UltraTech Cement',
  'ACC Ltd',
  'Ambuja Cements',
  'Thermax',
  'Siemens India',
  'ABB India',
  'Bharat Forge',
  'Bosch India',
  'Cummins India',
  'Kirloskar',
  'Godrej & Boyce',
  'Havells India',
  'Voltas',
  'Blue Star',
  'Crompton Greaves',
  'Finolex Cables',
  'Polycab India',
  'Dixon Technologies',
  'Amber Enterprises',
  'Kaynes Technology',
  'IBM Consulting',
  'Atos',
  'DXC Technology',
  'NTT Data',
  'Publicis Sapient',
  'Thoughtworks',
  'Slalom',
  'West Monroe',
  'Fractal Analytics',
  'Mu Sigma',
  'AbsolutData',
  'LatentView Analytics',
  'Tiger Analytics',
  'MathCo',
  'Tredence',
  'Amazon India',
  'Google India',
  'Microsoft India',
  'Meta India',
  'Apple India',
  'Uber India',
  'Myntra',
  'Ajio',
  'Adobe India',
  'Salesforce India',
  'SAP India',
  'Oracle India',
  'VMware India',
  'Cisco India',
  'Intel India',
  'Qualcomm India',
  'Texas Instruments India',
  'Samsung India',
  'LG India',
  'Sony India',
  'Honeywell India',
  'GE India',
  '3M India',
  'Schneider Electric India',
  'Caterpillar India',
  'John Deere India',
  'Bayer India',
  'BASF India',
  'Henkel India',
  'Alstom India',
  'Hitachi India',
  'Panasonic India',
  'Toshiba India',
  'NEC India',
  'Fujitsu India',
  'Ericsson India',
  'Nokia India',
  'ZTE India',
  'Huawei India',
  'Lenovo India',
  'Xiaomi India',
  'Oppo India',
  'Vivo India',
  'realme India',
  'Goldman Sachs India',
  'JP Morgan India',
  'Morgan Stanley India',
  'Barclays India',
  'Deutsche Bank India',
  'Credit Suisse India',
  'UBS India',
  'Citibank India',
  'HSBC India',
  'Standard Chartered India',
  'BNP Paribas India',
  'Societe Generale India',
  'Nomura India',
  'Bank of America India',
  'Wells Fargo India',
  'Reliance Energy',
  'Adani Power',
  'Tata Power',
  'NHPC',
  'SJVN',
  'Torrent Power',
  'CESC',
  'JSW Energy',
  'Adani Green Energy',
  'ReNew Energy',
  'Suzlon Energy',
  'Tata Renewables',
  'Azure Power',
  'Hero Future Energies',
  'Sterlite Power',
  'Adani Transmission',
  'GMR Group',
  'GVK Group',
  'IRB Infrastructure',
  'NCC Limited',
  'KEC International',
  'Kalpataru Projects',
  'Dilip Buildcon',
  'PNC Infratech',
  'HG Infra',
  'Afcons Infrastructure',
  'Shapoorji Pallonji',
  'Reliance Jio',
  'Bharti Airtel',
  'Vodafone Idea',
  'Tata Communications',
  'Sterlite Technologies',
  'Tejas Networks',
  'Route Mobile',
  'Affle India',
  'Nazara Technologies',
] as const;

export const CERTIFICATION_SUGGESTIONS = [
  // Cloud - AWS
  'AWS Solutions Architect - Associate',
  'AWS Solutions Architect - Professional',
  'AWS Developer Associate',
  'AWS DevOps Engineer',
  'AWS SysOps Administrator',
  'AWS Security Specialty',
  'AWS Machine Learning Specialty',
  'AWS Database Specialty',
  'AWS Data Analytics Specialty',
  'AWS Advanced Networking Specialty',
  // Cloud - Azure
  'Azure Administrator (AZ-104)',
  'Azure Developer (AZ-204)',
  'Azure Solutions Architect (AZ-305)',
  'Azure DevOps Engineer (AZ-400)',
  'Azure Security Engineer (AZ-500)',
  'Azure Data Engineer (DP-203)',
  'Azure AI Engineer (AI-102)',
  'Azure Fundamentals (AZ-900)',
  // Cloud - Google
  'Google Cloud Professional Cloud Architect',
  'Google Cloud Professional Data Engineer',
  'Google Cloud Professional ML Engineer',
  'Google Cloud Associate Cloud Engineer',
  'Google Cloud Professional DevOps Engineer',
  'Google Cloud Professional Security Engineer',
  // Development
  'Oracle Certified Java Programmer',
  'Microsoft Certified: Azure Developer',
  'Certified Kubernetes Administrator (CKA)',
  'Certified Kubernetes Developer (CKAD)',
  'Docker Certified Associate',
  'MongoDB Certified Developer',
  'Salesforce Certified Administrator',
  'Salesforce Certified Developer',
  'Salesforce Certified Architect',
  'Red Hat Certified System Administrator (RHCSA)',
  'Red Hat Certified Engineer (RHCE)',
  'HashiCorp Terraform Associate',
  'HashiCorp Vault Associate',
  'Linux Foundation Certified System Administrator',
  // Data & AI
  'TensorFlow Developer Certificate',
  'IBM Data Science Professional',
  'Google Data Analytics Professional',
  'Microsoft Power BI Data Analyst',
  'Databricks Certified Data Engineer',
  'Databricks Certified ML Professional',
  'Snowflake SnowPro Core',
  'Tableau Desktop Specialist',
  'Tableau Certified Data Analyst',
  'SAS Certified Data Scientist',
  'Cloudera Certified Data Analyst',
  'dbt Analytics Engineering Certification',
  'Apache Spark Developer Certification',
  // Project Management & Agile
  'PMP (Project Management Professional)',
  'Certified Scrum Master (CSM)',
  'PRINCE2 Practitioner',
  'PMI-ACP (Agile Certified Practitioner)',
  'SAFe Agilist',
  'SAFe Scrum Master',
  'SAFe Product Owner',
  'Six Sigma Green Belt',
  'Six Sigma Black Belt',
  'Six Sigma Yellow Belt',
  'Lean Six Sigma',
  'ITIL 4 Foundation',
  'ITIL 4 Managing Professional',
  'TOGAF 10 Certified',
  'COBIT Foundation',
  'Certified Product Manager (CPM)',
  // Security
  'CISSP',
  'CEH (Certified Ethical Hacker)',
  'CompTIA Security+',
  'OSCP',
  'CISM (Certified Information Security Manager)',
  'CISA (Certified Information Systems Auditor)',
  'CompTIA Network+',
  'CompTIA Linux+',
  'CompTIA A+',
  'CompTIA CySA+',
  'CompTIA PenTest+',
  'GIAC Security Essentials (GSEC)',
  'Certified Cloud Security Professional (CCSP)',
  'SOC 2 Type II',
  'ISO 27001 Lead Auditor',
  // Networking
  'Cisco CCNA',
  'Cisco CCNP',
  'Cisco CCIE',
  'Juniper JNCIA',
  // Design & Marketing
  'Google UX Design Certificate',
  'Meta Frontend Developer',
  'HubSpot Inbound Marketing',
  'HubSpot Content Marketing',
  'HubSpot Sales Software',
  'Google Analytics Certification',
  'Google Ads Certification',
  'Meta Blueprint Certification',
  'Adobe Certified Expert',
  'Figma Professional Certification',
  // Others
  'Certified ScrumMaster (CSM)',
  'Professional Scrum Master (PSM)',
  'Microsoft 365 Certified',
  'ServiceNow Certified System Administrator',
  'Workday Certified',
  'SAP Certified Application Associate',
  'SAP ABAP Developer',
] as const;

export const LANGUAGE_SUGGESTIONS = [
  'English',
  'Hindi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Gujarati',
  'Bengali',
  'Punjabi',
  'Odia',
  'Assamese',
  'Urdu',
  'Sanskrit',
  'Konkani',
  'Manipuri',
  'Nepali',
  'French',
  'German',
  'Spanish',
  'Japanese',
  'Mandarin Chinese',
  'Korean',
  'Arabic',
  'Portuguese',
  'Italian',
  'Russian',
] as const;

export const BENEFIT_SUGGESTIONS = [
  // Health & Insurance
  'Health Insurance',
  'Life Insurance',
  'Dental Coverage',
  'Vision Coverage',
  'Mental Health Support',
  'Gym Membership',
  'Wellness Programs',
  // Leave & Time Off
  'Paid Vacation',
  'Sick Leave',
  'Maternity Leave',
  'Paternity Leave',
  'Period Leave',
  'Sabbatical',
  'Bereavement Leave',
  'Comp-Off',
  // Financial
  'Performance Bonus',
  'Stock Options (ESOPs)',
  'Profit Sharing',
  'Gratuity',
  'Provident Fund',
  'Annual Increment',
  'Relocation Allowance',
  // Work-Life
  'Work From Home',
  'Flexible Hours',
  'Hybrid Work',
  'No Notice Period',
  'Compressed Work Week',
  'Remote Work',
  '5-Day Work Week',
  // Learning
  'Education Reimbursement',
  'Training Budget',
  'Conference Attendance',
  'Online Course Subscriptions',
  'Certification Reimbursement',
  // Office & Others
  'Free Meals',
  'Cafeteria',
  'Transport Allowance',
  'Cab Facility',
  'Team Outings',
  'Game Room',
  'Creche/Daycare',
  'Parking',
  'Employee Referral Bonus',
  'Joining Bonus',
  'Retention Bonus',
  'Mobile Reimbursement',
  'Internet Allowance',
  'Laptop Provided',
] as const;

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Chandigarh',
  'Delhi',
  'Jammu & Kashmir',
  'Ladakh',
  'Puducherry',
  'Andaman & Nicobar Islands',
  'Lakshadweep',
  'Dadra & Nagar Haveli and Daman & Diu',
] as const;

export const REVENUE_RANGE_OPTIONS = [
  'Less than ₹1 Crore',
  '₹1 - ₹10 Crore',
  '₹10 - ₹50 Crore',
  '₹50 - ₹100 Crore',
  '₹100 - ₹500 Crore',
  '₹500 - ₹1000 Crore',
  '₹1000 - ₹5000 Crore',
  'More than ₹5000 Crore',
] as const;

export const VISA_STATUS_OPTIONS = [
  'Indian Citizen',
  'OCI Card Holder',
  'PIO Card Holder',
  'H-1B Visa',
  'L-1 Visa',
  'Work Permit',
  'Student Visa',
  'PR (Permanent Resident)',
  'Not Applicable',
] as const;

export const VOLUNTEER_CAUSE_SUGGESTIONS = [
  'Animal Welfare',
  'Arts and Culture',
  'Children',
  'Civil Rights',
  'Disaster Relief',
  'Education',
  'Environment',
  'Health',
  'Human Rights',
  'Hunger',
  'Poverty Alleviation',
  'Science and Technology',
  'Senior Citizens',
  'Social Services',
  'Women Empowerment',
  'Youth Development',
  'Community Development',
  'Rural Development',
  'Digital Literacy',
  'Mental Health',
] as const;

export const HOBBY_SUGGESTIONS = [
  'Reading',
  'Writing',
  'Blogging',
  'Photography',
  'Videography',
  'Cooking',
  'Baking',
  'Gardening',
  'Painting',
  'Drawing',
  'Sketching',
  'Music',
  'Singing',
  'Dancing',
  'Playing Guitar',
  'Playing Piano',
  'Travelling',
  'Trekking',
  'Hiking',
  'Cycling',
  'Running',
  'Swimming',
  'Cricket',
  'Football',
  'Badminton',
  'Tennis',
  'Chess',
  'Table Tennis',
  'Yoga',
  'Meditation',
  'Fitness',
  'Gym',
  'CrossFit',
  'Martial Arts',
  'Gaming',
  'Coding',
  'Open Source',
  'DIY Projects',
  'Electronics',
  'Volunteering',
  'Public Speaking',
  'Debating',
  'Stand-up Comedy',
  'Astronomy',
  'Bird Watching',
  'Calligraphy',
  'Origami',
  'Pottery',
  'Film Making',
  'Podcasting',
  'Content Creation',
  'Social Media',
] as const;

export const INTEREST_SUGGESTIONS = [
  'Artificial Intelligence',
  'Machine Learning',
  'Blockchain',
  'Web3',
  'Cryptocurrency',
  'Startups',
  'Entrepreneurship',
  'Venture Capital',
  'Product Management',
  'Cloud Computing',
  'Cybersecurity',
  'Data Science',
  'IoT',
  'Robotics',
  'Sustainability',
  'Clean Energy',
  'Climate Tech',
  'AgriTech',
  'FinTech',
  'EdTech',
  'HealthTech',
  'SpaceTech',
  'BioTech',
  'UX Design',
  'Design Thinking',
  'Leadership',
  'Mentoring',
  'Stock Market',
  'Personal Finance',
  'Real Estate',
  'Economics',
  'Psychology',
  'Philosophy',
  'History',
  'Politics',
  'Geopolitics',
  'Open Source Software',
  'Developer Community',
  'Technical Writing',
  'Public Policy',
  'Social Impact',
  'Diversity & Inclusion',
] as const;

export const PROFESSIONAL_ORGANIZATION_SUGGESTIONS = [
  'IEEE',
  'ACM',
  'NASSCOM',
  'CII',
  'FICCI',
  'IETE',
  'CSI (Computer Society of India)',
  'ISCA',
  'PMI (Project Management Institute)',
  'SHRM',
  'CIPD',
  'ICAI (Institute of Chartered Accountants)',
  'ICSI',
  'ICWAI',
  'Bar Council of India',
  'Medical Council of India',
  'IEI (Institution of Engineers)',
  'ISTE',
  'Indian Physics Association',
  'Indian Chemical Society',
  'Institution of Mechanical Engineers',
  'Institution of Civil Engineers',
  'Data Science Society',
  'AI & ML India',
  'Google Developer Groups',
  'AWS User Group',
  'Microsoft MVP Program',
  'GitHub Campus Expert',
] as const;

export const TEST_SCORE_SUGGESTIONS = [
  'GRE',
  'GMAT',
  'CAT',
  'XAT',
  'MAT',
  'CMAT',
  'SNAP',
  'NMAT',
  'GATE',
  'NET/SET',
  'UGC NET',
  'CSIR NET',
  'TOEFL',
  'IELTS',
  'PTE',
  'Duolingo English Test',
  'AMCAT',
  'CoCubes',
  'eLitmus',
  'Wheebox',
  'HackerRank',
  'LeetCode',
  'CodeChef Rating',
  'Codeforces Rating',
  'AWS Certification Score',
  'Google Cloud Score',
  'Azure Score',
  'SAT',
  'ACT',
  'JEE Main',
  'JEE Advanced',
  'BITSAT',
  'VITEEE',
] as const;

export const SUB_INDUSTRY_SUGGESTIONS = [
  // IT Sub-industries
  'SaaS',
  'PaaS',
  'Cloud Infrastructure',
  'Cybersecurity',
  'AI/ML',
  'Data Analytics',
  'IT Consulting',
  'IT Services',
  'Product Development',
  // FinTech Sub-industries
  'Payments',
  'Lending',
  'InsurTech',
  'WealthTech',
  'RegTech',
  'Neo Banking',
  // E-Commerce Sub-industries
  'B2B Commerce',
  'B2C Commerce',
  'D2C',
  'Marketplace',
  'Quick Commerce',
  // HealthTech Sub-industries
  'Telemedicine',
  'Health Analytics',
  'Medical Devices',
  'Digital Health',
  // EdTech Sub-industries
  'K-12',
  'Higher Education',
  'Test Prep',
  'Skill Development',
  'Corporate Training',
  // Others
  'Logistics Tech',
  'PropTech',
  'AgriTech',
  'FoodTech',
  'CleanTech',
  'SpaceTech',
  'Gaming',
  'Media Streaming',
  'Social Media',
  'AdTech',
  'HRTech',
  'LegalTech',
  'Construction Tech',
  'AutoTech',
  'Retail Tech',
] as const;

export const CORE_VALUE_SUGGESTIONS = [
  'Innovation',
  'Integrity',
  'Excellence',
  'Collaboration',
  'Customer First',
  'Transparency',
  'Accountability',
  'Diversity & Inclusion',
  'Sustainability',
  'Continuous Learning',
  'Empowerment',
  'Respect',
  'Trust',
  'Agility',
  'Ownership',
  'Passion',
  'Quality',
  'Teamwork',
  'Meritocracy',
  'Empathy',
] as const;

export const INVESTOR_SUGGESTIONS = [
  // Indian VCs
  'Sequoia Capital India',
  'Accel Partners',
  'Matrix Partners India',
  'Nexus Venture Partners',
  'Blume Ventures',
  'Elevation Capital',
  'Peak XV Partners',
  'Tiger Global',
  'Lightspeed India',
  'India Quotient',
  'Chiratae Ventures',
  'Kalaari Capital',
  'DST Global',
  'SoftBank Vision Fund',
  'Steadview Capital',
  'Jungle Ventures',
  '3one4 Capital',
  'Prime Venture Partners',
  'Stellaris Venture Partners',
  'Fireside Ventures',
  // Global VCs
  'Andreessen Horowitz (a16z)',
  'Y Combinator',
  'General Catalyst',
  'Insight Partners',
  'GGV Capital',
  'Falcon Edge',
  'Coatue Management',
  'B Capital Group',
  'Goldman Sachs',
  'Morgan Stanley',
  'Temasek',
  'GIC',
] as const;

export const PRODUCT_SERVICE_SUGGESTIONS = [
  'Enterprise Software',
  'Mobile Applications',
  'Web Applications',
  'API Services',
  'Cloud Solutions',
  'Data Platform',
  'AI/ML Platform',
  'Analytics Dashboard',
  'Payment Gateway',
  'CRM Software',
  'ERP Solutions',
  'HRMS',
  'ATS',
  'Marketing Automation',
  'Customer Support Platform',
  'E-Commerce Platform',
  'Supply Chain Management',
  'Inventory Management',
  'Accounting Software',
  'Learning Management System',
  'Project Management Tool',
  'Communication Platform',
  'Security Solutions',
  'IoT Platform',
  'Blockchain Solutions',
  'Consulting Services',
  'Managed Services',
  'Staff Augmentation',
  'Digital Transformation',
] as const;

export const NATIONALITY_SUGGESTIONS = [
  'Indian',
  'American',
  'British',
  'Canadian',
  'Australian',
  'German',
  'French',
  'Japanese',
  'Chinese',
  'Korean',
  'Singaporean',
  'Emirati',
  'Saudi',
  'Dutch',
  'Swedish',
  'Swiss',
  'Irish',
  'New Zealander',
  'Malaysian',
  'Bangladeshi',
  'Nepalese',
  'Sri Lankan',
  'Pakistani',
  'South African',
  'Brazilian',
  'Israeli',
  'Thai',
  'Filipino',
  'Indonesian',
  'Vietnamese',
  'Italian',
  'Spanish',
  'Russian',
] as const;

export const COUNTRY_SUGGESTIONS = [
  'India',
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Japan',
  'China',
  'South Korea',
  'Singapore',
  'United Arab Emirates',
  'Saudi Arabia',
  'Netherlands',
  'Sweden',
  'Switzerland',
  'Ireland',
  'New Zealand',
  'Malaysia',
  'Bangladesh',
  'Nepal',
  'Sri Lanka',
  'Pakistan',
  'South Africa',
  'Brazil',
  'Israel',
  'Thailand',
  'Philippines',
  'Indonesia',
  'Vietnam',
  'Italy',
  'Spain',
  'Russia',
  'Denmark',
  'Norway',
  'Finland',
  'Belgium',
  'Austria',
  'Poland',
  'Czech Republic',
  'Portugal',
  'Taiwan',
  'Hong Kong',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'Kenya',
  'Nigeria',
  'Egypt',
  'Turkey',
  'Mexico',
  'Argentina',
  'Chile',
] as const;

export const PUBLISHER_SUGGESTIONS = [
  'IEEE',
  'ACM',
  'Springer',
  'Elsevier',
  'Wiley',
  'Nature Publishing Group',
  'Oxford University Press',
  'Cambridge University Press',
  'Taylor & Francis',
  'Sage Publications',
  'Emerald Publishing',
  'Inderscience',
  'MDPI',
  'IOP Publishing',
  'Royal Society',
  'ArXiv',
  'SSRN',
  'ResearchGate',
  'Medium',
  'Dev.to',
  'Towards Data Science',
  'HackerNoon',
  'freeCodeCamp',
  'InfoQ',
  "O'Reilly Media",
  'Packt Publishing',
  'Manning Publications',
  'Apress',
  'Pearson',
  'McGraw-Hill',
  'PHI Learning',
] as const;

export const ERG_SUGGESTIONS = [
  'Women in Tech',
  'LGBTQ+ Alliance',
  'Black Professionals Network',
  'Asian Professionals Network',
  'Hispanic/Latinx Network',
  'Veterans Network',
  'Parents and Caregivers',
  'Disability Inclusion',
  'Women in Leadership',
  'Young Professionals',
  'Sustainability Champions',
  'Mental Health Advocates',
  'Neurodiversity Alliance',
  'Multi-Faith Network',
  'Remote Workers Guild',
  'First-Generation Professionals',
  'Working Mothers Forum',
  'Accessibility Champions',
  'Cultural Exchange Group',
  'Wellness Warriors',
] as const;

export const JOB_TITLE_SUGGESTIONS = [
  // Engineering
  'Software Engineer',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Principal Software Engineer',
  'Distinguished Engineer',
  'Software Architect',
  'Frontend Developer',
  'Senior Frontend Developer',
  'Backend Developer',
  'Senior Backend Developer',
  'Full Stack Developer',
  'Senior Full Stack Developer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'React Developer',
  'React Native Developer',
  'Angular Developer',
  'Vue.js Developer',
  'Node.js Developer',
  'Python Developer',
  'Java Developer',
  '.NET Developer',
  'Go Developer',
  'Rust Developer',
  'PHP Developer',
  'Ruby on Rails Developer',
  'Embedded Software Engineer',
  'Firmware Engineer',
  'Systems Programmer',
  'Compiler Engineer',
  'Graphics Engineer',
  'Game Developer',
  'Blockchain Developer',
  'Smart Contract Developer',
  'Web3 Developer',
  // DevOps & Infrastructure
  'DevOps Engineer',
  'Senior DevOps Engineer',
  'Site Reliability Engineer',
  'Platform Engineer',
  'Infrastructure Engineer',
  'Cloud Engineer',
  'Cloud Architect',
  'Solutions Architect',
  'Technical Architect',
  'Enterprise Architect',
  'Network Engineer',
  'Systems Administrator',
  'Linux Administrator',
  'Database Administrator',
  'Release Engineer',
  'Build Engineer',
  // Engineering Leadership
  'Tech Lead',
  'Engineering Manager',
  'Senior Engineering Manager',
  'Director of Engineering',
  'VP of Engineering',
  'SVP of Engineering',
  'CTO',
  'Chief Architect',
  // Data & AI
  'Data Analyst',
  'Senior Data Analyst',
  'Lead Data Analyst',
  'Data Scientist',
  'Senior Data Scientist',
  'Lead Data Scientist',
  'Principal Data Scientist',
  'ML Engineer',
  'Senior ML Engineer',
  'MLOps Engineer',
  'AI Engineer',
  'AI Research Scientist',
  'NLP Engineer',
  'Computer Vision Engineer',
  'Data Engineer',
  'Senior Data Engineer',
  'Lead Data Engineer',
  'Analytics Engineer',
  'BI Developer',
  'BI Analyst',
  'Data Architect',
  'Chief Data Officer',
  'Head of Data Science',
  'Head of Analytics',
  // Product
  'Product Manager',
  'Senior Product Manager',
  'Group Product Manager',
  'Director of Product',
  'VP of Product',
  'Chief Product Officer',
  'Product Owner',
  'Product Analyst',
  'Technical Product Manager',
  'Growth Product Manager',
  'Associate Product Manager',
  // Design
  'UI Designer',
  'UX Designer',
  'UI/UX Designer',
  'Product Designer',
  'Senior Product Designer',
  'Lead Designer',
  'Design Manager',
  'Head of Design',
  'VP of Design',
  'Chief Design Officer',
  'UX Researcher',
  'UX Writer',
  'Visual Designer',
  'Interaction Designer',
  'Motion Designer',
  'Brand Designer',
  'Graphic Designer',
  'Creative Director',
  // QA & Testing
  'QA Engineer',
  'Senior QA Engineer',
  'QA Lead',
  'QA Manager',
  'Test Automation Engineer',
  'SDET',
  'Performance Test Engineer',
  'Security Test Engineer',
  'QA Architect',
  // Security
  'Security Engineer',
  'Senior Security Engineer',
  'Application Security Engineer',
  'Cloud Security Engineer',
  'Security Analyst',
  'SOC Analyst',
  'Penetration Tester',
  'Security Architect',
  'CISO',
  'Head of Information Security',
  'Incident Response Analyst',
  'Threat Intelligence Analyst',
  'GRC Analyst',
  // Marketing
  'Marketing Executive',
  'Marketing Manager',
  'Senior Marketing Manager',
  'Digital Marketing Manager',
  'Content Marketing Manager',
  'SEO Specialist',
  'SEM Specialist',
  'Social Media Manager',
  'Brand Manager',
  'Senior Brand Manager',
  'Growth Manager',
  'Growth Hacker',
  'Performance Marketing Manager',
  'Marketing Analyst',
  'CMO',
  'VP of Marketing',
  'Head of Marketing',
  'Email Marketing Specialist',
  'Copywriter',
  'Senior Copywriter',
  'Content Writer',
  'Content Strategist',
  'Communications Manager',
  'PR Manager',
  'Influencer Marketing Manager',
  'Affiliate Marketing Manager',
  'Category Manager',
  'Trade Marketing Manager',
  // Sales
  'Sales Executive',
  'Sales Manager',
  'Senior Sales Manager',
  'Account Executive',
  'Account Manager',
  'Key Account Manager',
  'Business Development Executive',
  'Business Development Manager',
  'Senior Business Development Manager',
  'Regional Sales Manager',
  'Area Sales Manager',
  'Zonal Sales Manager',
  'National Sales Manager',
  'VP of Sales',
  'Chief Revenue Officer',
  'Sales Engineer',
  'Pre-Sales Consultant',
  'Inside Sales Representative',
  'Channel Sales Manager',
  'Enterprise Sales Manager',
  'Sales Operations Manager',
  'Sales Enablement Manager',
  // HR & People
  'HR Executive',
  'HR Manager',
  'Senior HR Manager',
  'HR Business Partner',
  'Talent Acquisition Specialist',
  'Recruiter',
  'Senior Recruiter',
  'Technical Recruiter',
  'Recruitment Manager',
  'Head of Talent Acquisition',
  'L&D Manager',
  'Training Manager',
  'Compensation & Benefits Manager',
  'Employee Relations Manager',
  'HR Director',
  'VP of HR',
  'CHRO',
  'People Operations Manager',
  'Organizational Development Specialist',
  'HRIS Analyst',
  'HR Analyst',
  'Payroll Manager',
  // Finance & Accounting
  'Accountant',
  'Senior Accountant',
  'Financial Analyst',
  'Senior Financial Analyst',
  'Finance Manager',
  'Senior Finance Manager',
  'FP&A Analyst',
  'FP&A Manager',
  'Controller',
  'Treasurer',
  'Tax Analyst',
  'Tax Manager',
  'Audit Manager',
  'Internal Auditor',
  'External Auditor',
  'CFO',
  'VP of Finance',
  'Head of Finance',
  'Investment Analyst',
  'Portfolio Manager',
  'Risk Analyst',
  'Risk Manager',
  'Compliance Officer',
  'Compliance Manager',
  'Company Secretary',
  'Revenue Analyst',
  'Billing Analyst',
  'Accounts Payable Specialist',
  'Accounts Receivable Specialist',
  'Credit Analyst',
  // Legal
  'Legal Counsel',
  'Senior Legal Counsel',
  'General Counsel',
  'Corporate Lawyer',
  'IP Lawyer',
  'Employment Lawyer',
  'Legal Manager',
  'Head of Legal',
  'Chief Legal Officer',
  'Contract Manager',
  'Paralegal',
  'Legal Associate',
  // Operations & Supply Chain
  'Operations Executive',
  'Operations Manager',
  'Senior Operations Manager',
  'VP of Operations',
  'COO',
  'Supply Chain Manager',
  'Logistics Manager',
  'Procurement Manager',
  'Warehouse Manager',
  'Fleet Manager',
  'Facility Manager',
  'Purchase Manager',
  'Vendor Manager',
  'Inventory Manager',
  'Planning Manager',
  'Process Improvement Manager',
  'Lean Manager',
  'Six Sigma Black Belt',
  // Customer Success & Support
  'Customer Support Executive',
  'Customer Support Manager',
  'Customer Success Manager',
  'Senior Customer Success Manager',
  'Customer Experience Manager',
  'Technical Support Engineer',
  'Help Desk Analyst',
  'Customer Success Director',
  'Head of Customer Success',
  'Implementation Manager',
  'Onboarding Specialist',
  // Healthcare
  'Doctor',
  'Surgeon',
  'Physician',
  'Nurse',
  'Staff Nurse',
  'Nursing Superintendent',
  'Pharmacist',
  'Clinical Research Associate',
  'Medical Officer',
  'Hospital Administrator',
  'Radiologist',
  'Pathologist',
  'Anesthesiologist',
  'Physiotherapist',
  'Lab Technician',
  'Medical Coder',
  'Medical Biller',
  'Dentist',
  'Optometrist',
  // Education
  'Teacher',
  'Professor',
  'Assistant Professor',
  'Associate Professor',
  'Lecturer',
  'Principal',
  'Dean',
  'Academic Director',
  'Instructional Designer',
  'Curriculum Developer',
  'Training Coordinator',
  'Academic Counselor',
  // Consulting
  'Consultant',
  'Senior Consultant',
  'Management Consultant',
  'Strategy Consultant',
  'Technology Consultant',
  'Associate Consultant',
  'Principal Consultant',
  'Partner',
  'Managing Director',
  'Engagement Manager',
  'Business Analyst',
  'Senior Business Analyst',
  'Lead Business Analyst',
  'Systems Analyst',
  'Functional Consultant',
  'SAP Consultant',
  'Oracle Consultant',
  'Salesforce Consultant',
  'ERP Consultant',
  // Project & Program Management
  'Project Manager',
  'Senior Project Manager',
  'Program Manager',
  'Senior Program Manager',
  'Technical Program Manager',
  'Scrum Master',
  'Agile Coach',
  'PMO Manager',
  'Delivery Manager',
  'Release Manager',
  // C-Suite & Executive
  'CEO',
  'COO',
  'CFO',
  'CTO',
  'CMO',
  'CHRO',
  'CIO',
  'CDO',
  'CPO',
  'CSO',
  'General Manager',
  'Managing Director',
  'President',
  'Executive Director',
  'Board Member',
  'Founder',
  'Co-Founder',
  // Technical Writing & Documentation
  'Technical Writer',
  'Senior Technical Writer',
  'Documentation Manager',
  'API Technical Writer',
  'Content Developer',
  // Other
  'Chartered Accountant',
  'Company Secretary',
  'Cost Accountant',
  'Civil Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Electronics Engineer',
  'Chemical Engineer',
  'Production Engineer',
  'Quality Engineer',
  'Safety Officer',
  'Environmental Engineer',
  'Research Scientist',
  'Research Associate',
  'Lab Manager',
  'Scientist',
  'Patent Analyst',
  'Economist',
  'Statistician',
  'Actuary',
  'Underwriter',
  'Claims Manager',
  'Relationship Manager',
  'Wealth Manager',
  'Branch Manager',
  'Retail Store Manager',
  'Merchandiser',
  'Visual Merchandiser',
  'Fashion Designer',
  'Interior Designer',
  'Architect',
  'Urban Planner',
  'Journalist',
  'Editor',
  'Sub-Editor',
  'News Anchor',
  'Photographer',
  'Videographer',
  'Video Editor',
  'Sound Engineer',
  'Animator',
  'VFX Artist',
  'Social Worker',
  'Psychologist',
  'Counselor',
] as const;

/**
 * Map of suggestion category keys → static fallback arrays.
 * Used by the `useSuggest` hook when the ES server is unavailable.
 * Category keys must match backend SUGGESTION_CATEGORIES values.
 */
export const SEED_SUGGESTIONS_MAP: Record<string, readonly string[]> = {
  skill: SKILL_SUGGESTIONS,
  industry: INDUSTRY_SUGGESTIONS,
  department: DEPARTMENT_SUGGESTIONS,
  role_category: ROLE_CATEGORY_SUGGESTIONS,
  location: LOCATION_SUGGESTIONS,
  institution: INSTITUTION_SUGGESTIONS,
  degree: DEGREE_SUGGESTIONS,
  field_of_study: FIELD_OF_STUDY_SUGGESTIONS,
  company: COMPANY_NAME_SUGGESTIONS,
  certification: CERTIFICATION_SUGGESTIONS,
  language: LANGUAGE_SUGGESTIONS,
  benefit: BENEFIT_SUGGESTIONS,
  indian_state: INDIAN_STATES,
  visa_status: VISA_STATUS_OPTIONS,
  volunteer_cause: VOLUNTEER_CAUSE_SUGGESTIONS,
  hobby: HOBBY_SUGGESTIONS,
  interest: INTEREST_SUGGESTIONS,
  professional_org: PROFESSIONAL_ORGANIZATION_SUGGESTIONS,
  test_score: TEST_SCORE_SUGGESTIONS,
  sub_industry: SUB_INDUSTRY_SUGGESTIONS,
  core_value: CORE_VALUE_SUGGESTIONS,
  investor: INVESTOR_SUGGESTIONS,
  product_service: PRODUCT_SERVICE_SUGGESTIONS,
  nationality: NATIONALITY_SUGGESTIONS,
  country: COUNTRY_SUGGESTIONS,
  publisher: PUBLISHER_SUGGESTIONS,
  erg: ERG_SUGGESTIONS,
  revenue_range: REVENUE_RANGE_OPTIONS,
  job_title: JOB_TITLE_SUGGESTIONS,
};
