# ============================================================
# Kafka — Network Policy
# Only backend can connect to broker port.
# Prometheus can scrape kafka-exporter metrics.
# ============================================================
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-netpol
  namespace: hire-adda
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - port: 9092
          protocol: TCP
    # Allow Prometheus to scrape kafka-exporter
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 9308
          protocol: TCP
  egress:
    # DNS only
    - to: []
      ports:
        - port: 53
          protocol: UDP
